@startuml
class BattleLogEntry_StateTransition {
    + BattleLogEntry_StateTransition()
    + BattleLogEntry_StateTransition(subject:Thing, transitionDef:RulePackDef, initiator:Pawn, culpritHediff:Hediff, culpritTargetDef:BodyPartRecord)
    + <<override>> Concerns(t:Thing) : bool
    + <<override>> GetConcerns() : IEnumerable<Thing>
    + <<override>> CanBeClickedFromPOV(pov:Thing) : bool
    + <<override>> ClickedFromPOV(pov:Thing) : void
    + <<override>> IconFromPOV(pov:Thing) : Texture2D
    + <<override>> ExposeData() : void
    + <<override>> ToString() : string
}
LogEntry <|-- BattleLogEntry_StateTransition
@enduml
