@startuml
class BattleLogEntry_RangedFire {
    + BattleLogEntry_RangedFire()
    + BattleLogEntry_RangedFire(initiator:Thing, target:Thing, weaponDef:ThingDef, projectileDef:ThingDef, burst:bool)
    + <<override>> Concerns(t:Thing) : bool
    + <<override>> GetConcerns() : IEnumerable<Thing>
    + <<override>> CanBeClickedFromPOV(pov:Thing) : bool
    + <<override>> ClickedFromPOV(pov:Thing) : void
    + <<override>> ShowInCompactView() : bool
    + <<override>> ExposeData() : void
    + <<override>> ToString() : string
}
LogEntry <|-- BattleLogEntry_RangedFire
@enduml
