@startuml
class ColorLibrary <<static>> {
}
ColorLibrary o-> "Red" Color
ColorLibrary o-> "Brown" Color
ColorLibrary o-> "Pink" Color
ColorLibrary o-> "Blue" Color
ColorLibrary o-> "Green" Color
ColorLibrary o-> "Purple" Color
ColorLibrary o-> "Black" Color
ColorLibrary o-> "Violet" Color
ColorLibrary o-> "Teal" Color
ColorLibrary o-> "Grey" Color
ColorLibrary o-> "Magenta" Color
ColorLibrary o-> "Orange" Color
ColorLibrary o-> "Yellow" Color
ColorLibrary o-> "Leather" Color
ColorLibrary o-> "LightPurple" Color
ColorLibrary o-> "LimeGreen" Color
ColorLibrary o-> "SkyBlue" Color
ColorLibrary o-> "LightGreen" Color
ColorLibrary o-> "LightBlue" Color
ColorLibrary o-> "DarkOrange" Color
ColorLibrary o-> "Sand" Color
ColorLibrary o-> "PastelGreen" Color
ColorLibrary o-> "Mint" Color
ColorLibrary o-> "LightOrange" Color
ColorLibrary o-> "BrightPink" Color
ColorLibrary o-> "DeepPurple" Color
ColorLibrary o-> "DarkBrown" Color
ColorLibrary o-> "Taupe" Color
ColorLibrary o-> "PeaGreen" Color
ColorLibrary o-> "PukeGreen" Color
ColorLibrary o-> "BlueGreen" Color
ColorLibrary o-> "Khaki" Color
ColorLibrary o-> "Burgundy" Color
ColorLibrary o-> "DarkTeal" Color
ColorLibrary o-> "BrickRed" Color
ColorLibrary o-> "RoyalPurple" Color
ColorLibrary o-> "Plum" Color
ColorLibrary o-> "Gold" Color
ColorLibrary o-> "BabyBlue" Color
ColorLibrary o-> "YellowGreen" Color
ColorLibrary o-> "BrightPurple" Color
ColorLibrary o-> "DarkRed" Color
ColorLibrary o-> "PaleBlue" Color
ColorLibrary o-> "GrassGreen" Color
ColorLibrary o-> "Navy" Color
ColorLibrary o-> "Aquamarine" Color
ColorLibrary o-> "BurntOrange" Color
ColorLibrary o-> "NeonGreen" Color
ColorLibrary o-> "BrightBlue" Color
ColorLibrary o-> "Rose" Color
ColorLibrary o-> "LightPink" Color
ColorLibrary o-> "Mustard" Color
ColorLibrary o-> "Indigo" Color
ColorLibrary o-> "Lime" Color
ColorLibrary o-> "DarkPink" Color
ColorLibrary o-> "OliveGreen" Color
ColorLibrary o-> "Peach" Color
ColorLibrary o-> "PaleGreen" Color
ColorLibrary o-> "LightBrown" Color
ColorLibrary o-> "HotPink" Color
ColorLibrary o-> "Lilac" Color
ColorLibrary o-> "NavyBlue" Color
ColorLibrary o-> "RoyalBlue" Color
ColorLibrary o-> "Beige" Color
ColorLibrary o-> "Salmon" Color
ColorLibrary o-> "Olive" Color
ColorLibrary o-> "Maroon" Color
ColorLibrary o-> "BrightGreen" Color
ColorLibrary o-> "DarkPurple" Color
ColorLibrary o-> "Mauve" Color
ColorLibrary o-> "ForestGreen" Color
ColorLibrary o-> "Aqua" Color
ColorLibrary o-> "Cyan" Color
ColorLibrary o-> "Tan" Color
ColorLibrary o-> "DarkBlue" Color
ColorLibrary o-> "Lavender" Color
ColorLibrary o-> "Turquoise" Color
ColorLibrary o-> "DarkGreen" Color
@enduml
