@startuml
abstract class DeathActionWorker {
    + <<virtual>> DangerousInMelee : bool <<get>>
    + {abstract} PawnDied(corpse:Corpse) : void
}
DeathActionWorker --> "DeathRules" RulePackDef
@enduml
