@startuml
class DebugViewSettings <<static>> {
    + {static} drawFog : bool = true
    + {static} drawSnow : bool = true
    + {static} drawTerrain : bool = true
    + {static} drawTerrainWater : bool = true
    + {static} drawThingsDynamic : bool = true
    + {static} drawThingsPrinted : bool = true
    + {static} drawShadows : bool = true
    + {static} drawLightingOverlay : bool = true
    + {static} drawWorldOverlays : bool = true
    + {static} drawPaths : bool = false
    + {static} drawCastPositionSearch : bool = false
    + {static} drawDestSearch : bool = false
    + {static} drawSectionEdges : bool = false
    + {static} drawRiverDebug : bool = false
    + {static} drawPawnDebug : bool = false
    + {static} drawPawnRotatorTarget : bool = false
    + {static} drawRegions : bool = false
    + {static} drawRegionLinks : bool = false
    + {static} drawRegionDirties : bool = false
    + {static} drawRegionTraversal : bool = false
    + {static} drawRegionThings : bool = false
    + {static} drawRooms : bool = false
    + {static} drawRoomGroups : bool = false
    + {static} drawPower : bool = false
    + {static} drawPowerNetGrid : bool = false
    + {static} drawOpportunisticJobs : bool = false
    + {static} drawTooltipEdges : bool = false
    + {static} drawRecordedNoise : bool = false
    + {static} drawFoodSearchFromMouse : bool = false
    + {static} drawPreyInfo : bool = false
    + {static} drawGlow : bool = false
    + {static} drawAvoidGrid : bool = false
    + {static} drawLords : bool = false
    + {static} drawDuties : bool = false
    + {static} drawShooting : bool = false
    + {static} drawInfestationChance : bool = false
    + {static} drawStealDebug : bool = false
    + {static} drawDeepResources : bool = false
    + {static} drawAttackTargetScores : bool = false
    + {static} drawInteractionCells : bool = false
    + {static} drawDoorsDebug : bool = false
    + {static} drawDestReservations : bool = false
    + {static} drawDamageRects : bool = false
    + {static} writeGame : bool = false
    + {static} writeSteamItems : bool = false
    + {static} writeConcepts : bool = false
    + {static} writeReservations : bool = false
    + {static} writePathCosts : bool = false
    + {static} writeFertility : bool = false
    + {static} writeLinkFlags : bool = false
    + {static} writeCover : bool = false
    + {static} writeCellContents : bool = false
    + {static} writeMusicManagerPlay : bool = false
    + {static} writeStoryteller : bool = false
    + {static} writePlayingSounds : bool = false
    + {static} writeSoundEventsRecord : bool = false
    + {static} writeMoteSaturation : bool = false
    + {static} writeSnowDepth : bool = false
    + {static} writeEcosystem : bool = false
    + {static} writeRecentStrikes : bool = false
    + {static} writeBeauty : bool = false
    + {static} writeListRepairableBldgs : bool = false
    + {static} writeListFilthInHomeArea : bool = false
    + {static} writeListHaulables : bool = false
    + {static} writeListMergeables : bool = false
    + {static} writeTotalSnowDepth : bool = false
    + {static} writeCanReachColony : bool = false
    + {static} writeMentalStateCalcs : bool = false
    + {static} writeWind : bool = false
    + {static} writeTerrain : bool = false
    + {static} writeApparelScore : bool = false
    + {static} writeWorkSettings : bool = false
    + {static} writeSkyManager : bool = false
    + {static} writeMemoryUsage : bool = false
    + {static} writeMapGameConditions : bool = false
    + {static} writeAttackTargets : bool = false
    + {static} logIncapChance : bool = false
    + {static} logInput : bool = false
    + {static} logApparelGeneration : bool = false
    + {static} logLordToilTransitions : bool = false
    + {static} logGrammarResolution : bool = false
    + {static} logCombatLogMouseover : bool = false
    + {static} logCauseOfDeath : bool = false
    + {static} logMapLoad : bool = false
    + {static} logTutor : bool = false
    + {static} logSignals : bool = false
    + {static} logWorldPawnGC : bool = false
    + {static} logTaleRecording : bool = false
    + {static} logHourlyScreenshot : bool = false
    + {static} logFilthSummary : bool = false
    + {static} debugApparelOptimize : bool = false
    + {static} showAllRoomStats : bool = false
    + {static} showFloatMenuWorkGivers : bool = false
    + {static} drawTerrainWaterToggled() : void
    + {static} drawShadowsToggled() : void
}
@enduml
