@startuml
class DefaultEmptyListAttribute {
    + DefaultEmptyListAttribute(type:Type)
    + <<override>> ObjIsDefault(obj:object) : bool
}
DefaultValueAttribute <|-- DefaultEmptyListAttribute
@enduml
