@startuml
class DesignationDragger {
    + Dragging : bool <<get>>
    + FailureReason : string <<get>>
    + StartDrag() : void
    + EndDrag() : void
    + DraggerUpdate() : void
    + DraggerOnGUI() : void
}
class "List`1"<T> {
}
DesignationDragger --> "DragCells<IntVec3>" "List`1"
@enduml
