@startuml
class Graphic_MotePulse {
    + <<override>> DrawWorker(loc:Vector3, rot:Rot4, thingDef:ThingDef, thing:Thing, extraRotation:float) : void
    + <<override>> ToString() : string
}
Graphic_Mote <|-- Graphic_MotePulse
@enduml
