@startuml
class GraphicRequest <<struct>> {
    + path : string
    + renderQueue : int
    + GraphicRequest(graphicClass:Type, path:string, shader:Shader, drawSize:Vector2, color:Color, colorTwo:Color, graphicData:GraphicData, renderQueue:int, shaderParameters:List<ShaderParameter>)
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object) : bool
    + Equals(other:GraphicRequest) : bool
}
class "IEquatable`1"<T> {
}
class "List`1"<T> {
}
"IEquatable`1" "<GraphicRequest>" <|-- GraphicRequest
GraphicRequest --> "graphicClass" Type
GraphicRequest --> "shader" Shader
GraphicRequest --> "drawSize" Vector2
GraphicRequest --> "color" Color
GraphicRequest --> "colorTwo" Color
GraphicRequest --> "graphicData" GraphicData
GraphicRequest --> "shaderParameters<ShaderParameter>" "List`1"
@enduml
