@startuml
class HediffComp_ChanceToRemove {
    + currentInterval : int
    + removeNextInterval : bool
    + <<override>> CompShouldRemove : bool <<get>>
    + <<override>> CompPostTick(severityAdjustment:float) : void
    + <<override>> CompExposeData() : void
    + <<override>> CompDebugString() : string
}
HediffComp <|-- HediffComp_ChanceToRemove
HediffComp_ChanceToRemove --> "Props" HediffCompProperties_ChanceToRemove
@enduml
