@startuml
class HediffComp_ChangeImplantLevel {
    + lastChangeLevelTick : int
    + <<override>> CompPostTick(severityAdjustment:float) : void
    + <<override>> CompExposeData() : void
}
HediffComp <|-- HediffComp_ChangeImplantLevel
HediffComp_ChangeImplantLevel --> "Props" HediffCompProperties_ChangeImplantLevel
@enduml
