@startuml
class HediffComp_GrowthMode {
    + <<override>> CompLabelInBracketsExtra : string <<get>>
    + <<override>> CompExposeData() : void
    + <<override>> CompPostPostAdd(dinfo:DamageInfo?) : void
    + <<override>> CompPostTick(severityAdjustment:float) : void
    + <<override>> CompDebugString() : string
}
HediffComp_SeverityPerDay <|-- HediffComp_GrowthMode
HediffComp_GrowthMode --> "growthMode" HediffGrowthMode
HediffComp_GrowthMode --> "Props" HediffCompProperties_GrowthMode
@enduml
