@startuml
class IntRange <<struct>> {
    + min : int
    + max : int
    + TrueMin : int <<get>>
    + TrueMax : int <<get>>
    + Average : float <<get>>
    + RandomInRange : int <<get>>
    + IntRange(min:int, max:int)
    + Lerped(lerpFactor:float) : int
    + {static} FromString(s:string) : IntRange
    + <<override>> ToString() : string
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object) : bool
    + Equals(other:IntRange) : bool
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<IntRange>" <|-- IntRange
IntRange --> "zero" IntRange
IntRange --> "one" IntRange
@enduml
