@startuml
class KeyBindingDefGenerator <<static>> {
    + {static} ImpliedKeyBindingCategoryDefs() : IEnumerable<KeyBindingCategoryDef>
    + {static} ImpliedKeyBindingDefs() : IEnumerable<KeyBindingDef>
}
@enduml
