@startuml
class LanguageWorker_Swedish {
    + <<override>> WithIndefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
    + <<override>> WithDefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
    + IsVowel(ch:char) : bool
}
LanguageWorker <|-- LanguageWorker_Swedish
@enduml
