@startuml
class LanguageWorker_Norwegian {
    + <<override>> WithIndefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
    + <<override>> WithDefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
}
LanguageWorker <|-- LanguageWorker_Norwegian
@enduml
