@startuml
class LanguageWorker_German {
    + <<override>> WithIndefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
    + <<override>> WithDefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
    + <<override>> OrdinalNumber(number:int, gender:Gender) : string
    + <<override>> Pluralize(str:string, gender:Gender, count:int) : string
}
LanguageWorker <|-- LanguageWorker_German
@enduml
