@startuml
class LanguageWorker_Portuguese {
    + <<override>> WithIndefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
    + <<override>> WithDefiniteArticle(str:string, gender:Gender, plural:bool, name:bool) : string
}
LanguageWorker <|-- LanguageWorker_Portuguese
@enduml
