@startuml
class LogEntryDef {
    + iconMiss : string
    + iconDamaged : string
    + iconDamagedFromInstigator : string
    + <<override>> PostLoad() : void
}
Def <|-- LogEntryDef
LogEntryDef --> "iconMissTex" Texture2D
LogEntryDef --> "iconDamagedTex" Texture2D
LogEntryDef --> "iconDamagedFromInstigatorTex" Texture2D
@enduml
