@startuml
class MapFileCompressor {
    + MapFileCompressor(map:Map)
    + ExposeData() : void
    + BuildCompressedString() : void
    + ThingsToSpawnAfterLoad() : IEnumerable<Thing>
}
IExposable <|-- MapFileCompressor
MapFileCompressor --> "compressibilityDecider" CompressibilityDecider
@enduml
