@startuml
class PatchOperation {
    + sourceFile : string
    + Apply(xml:XmlDocument) : bool
    + <<virtual>> Complete(modIdentifier:string) : void
}
enum Success {
    Normal,
    Invert,
    Always,
    Never,
}
PatchOperation +-- Success
@enduml
