@startuml
class PawnCapacityWorker {
    + <<virtual>> CalculateCapacityLevel(diffSet:HediffSet, impactors:List<PawnCapacityUtility.CapacityImpactor>) : float
    + <<virtual>> CanHaveCapacity(body:BodyDef) : bool
}
@enduml
