@startuml
class ScattererValidator_Buildable {
    + radius : int = 1
    + <<override>> Allows(c:IntVec3, map:Map) : bool
}
ScattererValidator <|-- ScattererValidator_Buildable
ScattererValidator_Buildable --> "affordance" TerrainAffordanceDef
@enduml
