@startuml
class SubEffecter_Sustainer {
    + SubEffecter_Sustainer(def:SubEffecterDef, parent:Effecter)
    + <<override>> SubEffectTick(A:TargetInfo, B:TargetInfo) : void
}
SubEffecter <|-- SubEffecter_Sustainer
@enduml
