@startuml
class SubEffecter_InteractSymbol {
    + SubEffecter_InteractSymbol(def:SubEffecterDef, parent:Effecter)
    + <<override>> SubEffectTick(A:TargetInfo, B:TargetInfo) : void
    + <<override>> SubCleanup() : void
}
SubEffecter <|-- SubEffecter_InteractSymbol
@enduml
