@startuml
class TemporaryThingDrawable {
    + ticksLeft : int
    + ExposeData() : void
}
IExposable <|-- TemporaryThingDrawable
TemporaryThingDrawable --> "thing" Thing
TemporaryThingDrawable --> "position" Vector3
@enduml
