@startuml
class TerrainAffordanceDef {
    + order : int
    + visualizeOnAffordanceOverlay : bool
    + blockAffordanceOverlay : bool
}
Def <|-- TerrainAffordanceDef
TerrainAffordanceDef o-> "affordanceOverlayColor" Color
@enduml
