@startuml
class TexButton {
}
TexButton o-> "CloseXBig" Texture2D
TexButton o-> "CloseXSmall" Texture2D
TexButton o-> "NextBig" Texture2D
TexButton o-> "DeleteX" Texture2D
TexButton o-> "ReorderUp" Texture2D
TexButton o-> "ReorderDown" Texture2D
TexButton o-> "Plus" Texture2D
TexButton o-> "Minus" Texture2D
TexButton o-> "Suspend" Texture2D
TexButton o-> "SelectOverlappingNext" Texture2D
TexButton o-> "Info" Texture2D
TexButton o-> "Rename" Texture2D
TexButton o-> "Banish" Texture2D
TexButton o-> "OpenStatsReport" Texture2D
TexButton o-> "RenounceTitle" Texture2D
TexButton o-> "Copy" Texture2D
TexButton o-> "Paste" Texture2D
TexButton o-> "Drop" Texture2D
TexButton o-> "Ingest" Texture2D
TexButton o-> "DragHash" Texture2D
TexButton o-> "ToggleLog" Texture2D
TexButton o-> "OpenDebugActionsMenu" Texture2D
TexButton o-> "OpenInspector" Texture2D
TexButton o-> "OpenInspectSettings" Texture2D
TexButton o-> "ToggleGodMode" Texture2D
TexButton o-> "TogglePauseOnError" Texture2D
TexButton o-> "ToggleTweak" Texture2D
TexButton o-> "Add" Texture2D
TexButton o-> "NewItem" Texture2D
TexButton o-> "Reveal" Texture2D
TexButton o-> "Collapse" Texture2D
TexButton o-> "Empty" Texture2D
TexButton o-> "Save" Texture2D
TexButton o-> "NewFile" Texture2D
TexButton o-> "RenameDev" Texture2D
TexButton o-> "Reload" Texture2D
TexButton o-> "Play" Texture2D
TexButton o-> "Stop" Texture2D
TexButton o-> "RangeMatch" Texture2D
TexButton o-> "InspectModeToggle" Texture2D
TexButton o-> "CenterOnPointsTex" Texture2D
TexButton o-> "CurveResetTex" Texture2D
TexButton o-> "QuickZoomHor1Tex" Texture2D
TexButton o-> "QuickZoomHor100Tex" Texture2D
TexButton o-> "QuickZoomHor20kTex" Texture2D
TexButton o-> "QuickZoomVer1Tex" Texture2D
TexButton o-> "QuickZoomVer100Tex" Texture2D
TexButton o-> "QuickZoomVer20kTex" Texture2D
TexButton o-> "IconBlog" Texture2D
TexButton o-> "IconForums" Texture2D
TexButton o-> "IconTwitter" Texture2D
TexButton o-> "IconBook" Texture2D
TexButton o-> "IconSoundtrack" Texture2D
TexButton o-> "ShowLearningHelper" Texture2D
TexButton o-> "ShowZones" Texture2D
TexButton o-> "ShowFertilityOverlay" Texture2D
TexButton o-> "ShowTerrainAffordanceOverlay" Texture2D
TexButton o-> "ShowBeauty" Texture2D
TexButton o-> "ShowRoomStats" Texture2D
TexButton o-> "ShowColonistBar" Texture2D
TexButton o-> "ShowRoofOverlay" Texture2D
TexButton o-> "AutoHomeArea" Texture2D
TexButton o-> "AutoRebuild" Texture2D
TexButton o-> "CategorizedResourceReadout" Texture2D
TexButton o-> "LockNorthUp" Texture2D
TexButton o-> "UsePlanetDayNightSystem" Texture2D
TexButton o-> "ShowExpandingIcons" Texture2D
TexButton o-> "ShowWorldFeatures" Texture2D
@enduml
