@startuml
enum ToStringStyle {
    Integer,
    FloatOne,
    FloatTwo,
    FloatThree,
    FloatMaxOne,
    FloatMaxTwo,
    FloatMaxThree,
    FloatTwoOrThree,
    PercentZero,
    PercentOne,
    PercentTwo,
    Temperature,
    TemperatureOffset,
    WorkAmount,
    Money,
}
@enduml
