@startuml
class AbstractShapeGenerator <<static>> {
    + {static} Generate(width:int, height:int, horizontalSymmetry:bool, verticalSymmetry:bool, allTruesMustBeConnected:bool, allowEnclosedFalses:bool, preferOutlines:bool, wipedCircleRadiusPct:float) : bool[,]
}
@enduml
