@startuml
class Alert_MonumentMarkerMissingBlueprints {
    + Alert_MonumentMarkerMissingBlueprints()
    + <<override>> GetReport() : AlertReport
}
Alert <|-- Alert_MonumentMarkerMissingBlueprints
@enduml
