@startuml
class Alert_LifeThreateningHediff {
    + <<override>> GetLabel() : string
    + <<override>> GetExplanation() : TaggedString
    + <<override>> GetReport() : AlertReport
}
Alert_Critical <|-- Alert_LifeThreateningHediff
@enduml
