@startuml
class Alert_AwaitingMedicalOperation {
    + <<override>> GetLabel() : string
    + <<override>> GetExplanation() : TaggedString
    + <<override>> GetReport() : AlertReport
}
Alert <|-- Alert_AwaitingMedicalOperation
@enduml
