@startuml
class Alert_NeedJoySources {
    + Alert_NeedJoySources()
    + <<override>> GetExplanation() : TaggedString
    + <<override>> GetReport() : AlertReport
}
Alert <|-- Alert_NeedJoySources
@enduml
