@startuml
class Area_BuildRoof {
    + <<override>> Label : string <<get>>
    + <<override>> ListPriority : int <<get>>
    + Area_BuildRoof()
    + Area_BuildRoof(areaManager:AreaManager)
    + <<override>> GetUniqueLoadID() : string
}
Area <|-- Area_BuildRoof
Area_BuildRoof --> "Color" Color
@enduml
