@startuml
class BillStoreModeDefOf <<static>> {
    {static} BillStoreModeDefOf()
}
BillStoreModeDefOf --> "DropOnFloor" BillStoreModeDef
BillStoreModeDefOf --> "BestStockpile" BillStoreModeDef
BillStoreModeDefOf --> "SpecificStockpile" BillStoreModeDef
@enduml
