@startuml
class Blueprint_Build {
    + <<override>> Label : string <<get>>
    + <<override>> ExposeData() : void
    + <<override>> EntityToBuildStuff() : ThingDef
    + <<override>> MaterialsNeeded() : List<ThingDefCountClass>
    + <<override>> GetGizmos() : IEnumerable<Gizmo>
    + <<override>> GetInspectString() : string
}
Blueprint <|-- Blueprint_Build
Blueprint_Build --> "stuffToUse" ThingDef
@enduml
