@startuml
class CellWithRadius <<struct>> {
    + <<readonly>> radius : float
    + CellWithRadius(c:IntVec3, r:float)
    + Equals(other:CellWithRadius) : bool
    + <<override>> Equals(obj:object) : bool
    + <<override>> GetHashCode() : int
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<CellWithRadius>" <|-- CellWithRadius
CellWithRadius --> "cell" IntVec3
@enduml
