@startuml
class CompAbilityEffect_ForceJob {
    + <<override>> Apply(target:LocalTargetInfo, dest:LocalTargetInfo) : void
}
CompAbilityEffect_WithDest <|-- CompAbilityEffect_ForceJob
CompAbilityEffect_ForceJob --> "Props" CompProperties_AbilityForceJob
@enduml
