@startuml
class CompCauseGameCondition {
    + Active : bool <<get>>
    + MyTile : int <<get>>
    + LinkWithSite(site:Site) : void
    + <<override>> PostPostMake() : void
    + <<override>> PostExposeData() : void
    + InAoE(tile:int) : bool
    + <<override>> CompTick() : void
    + <<override>> PostDestroy(mode:DestroyMode, previousMap:Map) : void
    + <<override>> CompInspectStringExtra() : string
    + <<virtual>> RandomizeSettings_NewTemp(points:float) : void
    + <<virtual>> RandomizeSettings_NewTemp_NewTemp(site:Site) : void
    + <<virtual>> RandomizeSettings() : void
}
class "IEnumerable`1"<T> {
}
ThingComp <|-- CompCauseGameCondition
CompCauseGameCondition --> "Props" CompProperties_CausesGameCondition
CompCauseGameCondition --> "ConditionDef" GameConditionDef
CompCauseGameCondition --> "CausedConditions<GameCondition>" "IEnumerable`1"
@enduml
