@startuml
class CompProperties_AbilityTransferEntropy {
    + targetReceivesEntropy : bool = true
    + CompProperties_AbilityTransferEntropy()
}
CompProperties_AbilityEffect <|-- CompProperties_AbilityTransferEntropy
@enduml
