@startuml
class CompPowerPlant {
    + <<override>> PostSpawnSetup(respawningAfterLoad:bool) : void
    + <<override>> PostDeSpawn(map:Map) : void
    + <<override>> CompTick() : void
    + UpdateDesiredPowerOutput() : void
}
CompPowerTrader <|-- CompPowerPlant
@enduml
