@startuml
class CompPowerPlantWind {
    + updateWeatherEveryXTicks : int = 250
    + <<override>> PostSpawnSetup(respawningAfterLoad:bool) : void
    + <<override>> PostDeSpawn(map:Map) : void
    + <<override>> PostExposeData() : void
    + <<override>> CompTick() : void
    + <<override>> PostDraw() : void
    + <<override>> CompInspectStringExtra() : string
}
CompPowerPlant <|-- CompPowerPlantWind
@enduml
