@startuml
class CompProperties_GeneratedName {
    + CompProperties_GeneratedName()
}
CompProperties <|-- CompProperties_GeneratedName
CompProperties_GeneratedName --> "nameMaker" RulePackDef
@enduml
