@startuml
class CompAbilityEffect_SocialInteraction {
    + <<override>> Apply(target:LocalTargetInfo, dest:LocalTargetInfo) : void
    + <<override>> CanApplyOn(target:LocalTargetInfo, dest:LocalTargetInfo) : bool
    + <<override>> Valid(target:LocalTargetInfo, throwMessages:bool) : bool
}
CompAbilityEffect <|-- CompAbilityEffect_SocialInteraction
CompAbilityEffect_SocialInteraction --> "Props" CompProperties_AbilitySocialInteraction
@enduml
