@startuml
class CompDeepScanner {
    + <<override>> PostDrawExtraSelectionOverlays() : void
    + ShouldShowDeepResourceOverlay() : bool
}
CompScanner <|-- CompDeepScanner
CompDeepScanner --> "Props" CompProperties_ScannerMineralsDeep
@enduml
