@startuml
class CompAbilityEffect_EffecterOnTarget {
    + <<override>> Apply(target:LocalTargetInfo, dest:LocalTargetInfo) : void
}
CompAbilityEffect <|-- CompAbilityEffect_EffecterOnTarget
CompAbilityEffect_EffecterOnTarget --> "Props" CompProperties_AbilityEffecterOnTarget
@enduml
