@startuml
class CompAssignableToPawn_Throne {
    + <<override>> CompInspectStringExtra() : string
    + <<override>> AssignedAnything(pawn:Pawn) : bool
    + <<override>> TryAssignPawn(pawn:Pawn) : void
    + <<override>> TryUnassignPawn(pawn:Pawn, sort:bool) : void
    + <<override>> PostExposeData() : void
}
class "IEnumerable`1"<T> {
}
CompAssignableToPawn <|-- CompAssignableToPawn_Throne
CompAssignableToPawn_Throne --> "AssigningCandidates<Pawn>" "IEnumerable`1"
@enduml
