@startuml
class ConceptDefOf <<static>> {
    {static} ConceptDefOf()
}
ConceptDefOf --> "CameraDolly" ConceptDef
ConceptDefOf --> "CameraZoom" ConceptDef
ConceptDefOf --> "TimeControls" ConceptDef
ConceptDefOf --> "Pause" ConceptDef
ConceptDefOf --> "Mining" ConceptDef
ConceptDefOf --> "Forbidding" ConceptDef
ConceptDefOf --> "ForbiddingDoors" ConceptDef
ConceptDefOf --> "EquippingWeapons" ConceptDef
ConceptDefOf --> "Stockpiles" ConceptDef
ConceptDefOf --> "GrowingFood" ConceptDef
ConceptDefOf --> "InfoCard" ConceptDef
ConceptDefOf --> "AnimalTaming" ConceptDef
ConceptDefOf --> "AnimalTraining" ConceptDef
ConceptDefOf --> "InspectRoomStats" ConceptDef
ConceptDefOf --> "TimeAssignments" ConceptDef
ConceptDefOf --> "Outfits" ConceptDef
ConceptDefOf --> "DrugPolicies" ConceptDef
ConceptDefOf --> "ClickingMessages" ConceptDef
ConceptDefOf --> "HostilityResponse" ConceptDef
ConceptDefOf --> "WorkTab" ConceptDef
ConceptDefOf --> "StorageTab" ConceptDef
ConceptDefOf --> "HistoryTab" ConceptDef
ConceptDefOf --> "BillsTab" ConceptDef
ConceptDefOf --> "Alerts" ConceptDef
ConceptDefOf --> "AllowedAreas" ConceptDef
ConceptDefOf --> "ShotAccuracyTooltip" ConceptDef
ConceptDefOf --> "ManualWorkPriorities" ConceptDef
ConceptDefOf --> "SpoilageAndFreezers" ConceptDef
ConceptDefOf --> "FormCaravan" ConceptDef
ConceptDefOf --> "ReformCaravan" ConceptDef
ConceptDefOf --> "Capturing" ConceptDef
ConceptDefOf --> "Rescuing" ConceptDef
ConceptDefOf --> "Drafting" ConceptDef
ConceptDefOf --> "HomeArea" ConceptDef
ConceptDefOf --> "PrisonerTab" ConceptDef
ConceptDefOf --> "OpeningComms" ConceptDef
ConceptDefOf --> "BuildOrbitalTradeBeacon" ConceptDef
ConceptDefOf --> "MedicalOperations" ConceptDef
ConceptDefOf --> "WorldCameraMovement" ConceptDef
ConceptDefOf --> "SetGrowingZonePlant" ConceptDef
ConceptDefOf --> "AnimalsDontAttackDoors" ConceptDef
ConceptDefOf --> "InteractingWithTraders" ConceptDef
ConceptDefOf --> "DrugAddiction" ConceptDef
ConceptDefOf --> "ShieldBelts" ConceptDef
ConceptDefOf --> "DrugBurning" ConceptDef
ConceptDefOf --> "DoorOpenSpeed" ConceptDef
ConceptDefOf --> "QueueOrders" ConceptDef
ConceptDefOf --> "MeditationSchedule" ConceptDef
ConceptDefOf --> "MeditationDesiredPsyfocus" ConceptDef
ConceptDefOf --> "ArrestingCreatesEnemies" ConceptDef
ConceptDefOf --> "TradeGoodsMustBeNearBeacon" ConceptDef
ConceptDefOf --> "SwitchFlickingDesignation" ConceptDef
ConceptDefOf --> "MaxNumberOfPlayerSettlements" ConceptDef
ConceptDefOf --> "TradingRequiresPermit" ConceptDef
@enduml
