@startuml
class DeathActionWorker_SmallExplosion {
    + <<override>> DangerousInMelee : bool <<get>>
    + <<override>> PawnDied(corpse:Corpse) : void
}
DeathActionWorker <|-- DeathActionWorker_SmallExplosion
DeathActionWorker_SmallExplosion --> "DeathRules" RulePackDef
@enduml
