@startuml
class Designator_SmoothSurface {
    + <<override>> DraggableDimensions : int <<get>>
    + <<override>> DragDrawMeasurements : bool <<get>>
    + Designator_SmoothSurface()
    + <<override>> CanDesignateThing(t:Thing) : AcceptanceReport
    + <<override>> DesignateThing(t:Thing) : void
    + <<override>> CanDesignateCell(c:IntVec3) : AcceptanceReport
    + <<override>> DesignateSingleCell(c:IntVec3) : void
    + <<override>> SelectedUpdate() : void
    + <<override>> RenderHighlight(dragCells:List<IntVec3>) : void
}
Designator <|-- Designator_SmoothSurface
@enduml
