@startuml
class Designator_Strip {
    + <<override>> DraggableDimensions : int <<get>>
    + Designator_Strip()
    + <<override>> CanDesignateCell(c:IntVec3) : AcceptanceReport
    + <<override>> DesignateSingleCell(c:IntVec3) : void
    + <<override>> CanDesignateThing(t:Thing) : AcceptanceReport
    + <<override>> DesignateThing(t:Thing) : void
}
Designator <|-- Designator_Strip
@enduml
