@startuml
class DesignationCategoryDefOf <<static>> {
    {static} DesignationCategoryDefOf()
}
DesignationCategoryDefOf --> "Production" DesignationCategoryDef
DesignationCategoryDefOf --> "Structure" DesignationCategoryDef
DesignationCategoryDefOf --> "Security" DesignationCategoryDef
DesignationCategoryDefOf --> "Floors" DesignationCategoryDef
@enduml
