@startuml
class Designator_Open {
    + <<override>> DraggableDimensions : int <<get>>
    + Designator_Open()
    + <<override>> CanDesignateCell(c:IntVec3) : AcceptanceReport
    + <<override>> DesignateSingleCell(c:IntVec3) : void
    + <<override>> CanDesignateThing(t:Thing) : AcceptanceReport
    + <<override>> DesignateThing(t:Thing) : void
}
Designator <|-- Designator_Open
@enduml
