@startuml
class Designator_PlantsCut {
    + Designator_PlantsCut()
    + <<override>> CanDesignateThing(t:Thing) : AcceptanceReport
    + <<override>> DesignateThing(t:Thing) : void
}
Designator_Plants <|-- Designator_PlantsCut
@enduml
