@startuml
class Dialog_SellableItems {
    + Dialog_SellableItems(trader:ITrader)
    + <<override>> DoWindowContents(inRect:Rect) : void
}
Window <|-- Dialog_SellableItems
Dialog_SellableItems --> "InitialSize" Vector2
@enduml
