@startuml
class DifficultyDefOf <<static>> {
    {static} DifficultyDefOf()
}
DifficultyDefOf --> "Peaceful" DifficultyDef
DifficultyDefOf --> "Easy" DifficultyDef
DifficultyDefOf --> "Rough" DifficultyDef
@enduml
