@startuml
class DifficultyConditionConfig {
    + bigThreatsDisabled : bool
    + trapsDisabled : bool
    + turretsDisabled : bool
    + mortarsDisabled : bool
    + extremeWeatherIncidentsDisabled : bool
}
@enduml
