@startuml
class GenStep_ConditionCauser {
    + <<override>> SeedPart : int <<get>>
    + <<override>> Generate(map:Map, parms:GenStepParams) : void
}
GenStep_Scatterer <|-- GenStep_ConditionCauser
@enduml
