@startuml
class GenStep_FindPlayerStartSpot {
    + <<override>> SeedPart : int <<get>>
    + <<override>> Generate(map:Map, parms:GenStepParams) : void
}
GenStep <|-- GenStep_FindPlayerStartSpot
@enduml
