@startuml
class Gizmo_RefuelableFuelStatus {
    + Gizmo_RefuelableFuelStatus()
    + <<override>> GetWidth(maxWidth:float) : float
    + <<override>> GizmoOnGUI(topLeft:Vector2, maxWidth:float) : GizmoResult
}
Gizmo <|-- Gizmo_RefuelableFuelStatus
Gizmo_RefuelableFuelStatus --> "refuelable" CompRefuelable
@enduml
