@startuml
class Hediff_Addiction {
    + <<override>> LabelInBrackets : string <<get>>
    + <<override>> TipStringExtra : string <<get>>
    + <<override>> CurStageIndex : int <<get>>
    + Notify_NeedCategoryChanged() : void
}
HediffWithComps <|-- Hediff_Addiction
Hediff_Addiction --> "Need" Need_Chemical
Hediff_Addiction --> "Chemical" ChemicalDef
@enduml
