@startuml
class HediffDefOf <<static>> {
    {static} HediffDefOf()
}
HediffDefOf --> "Misc" HediffDef
HediffDefOf --> "Burn" HediffDef
HediffDefOf --> "Cut" HediffDef
HediffDefOf --> "SurgicalCut" HediffDef
HediffDefOf --> "ExecutionCut" HediffDef
HediffDefOf --> "Stab" HediffDef
HediffDefOf --> "Gunshot" HediffDef
HediffDefOf --> "Shredded" HediffDef
HediffDefOf --> "Bruise" HediffDef
HediffDefOf --> "Bite" HediffDef
HediffDefOf --> "Scratch" HediffDef
HediffDefOf --> "MissingBodyPart" HediffDef
HediffDefOf --> "BloodLoss" HediffDef
HediffDefOf --> "Hypothermia" HediffDef
HediffDefOf --> "Heatstroke" HediffDef
HediffDefOf --> "Malnutrition" HediffDef
HediffDefOf --> "ToxicBuildup" HediffDef
HediffDefOf --> "PsychicShock" HediffDef
HediffDefOf --> "ResurrectionSickness" HediffDef
HediffDefOf --> "ResurrectionPsychosis" HediffDef
HediffDefOf --> "Anesthetic" HediffDef
HediffDefOf --> "CryptosleepSickness" HediffDef
HediffDefOf --> "FoodPoisoning" HediffDef
HediffDefOf --> "Pregnant" HediffDef
HediffDefOf --> "CatatonicBreakdown" HediffDef
HediffDefOf --> "Scaria" HediffDef
HediffDefOf --> "PsychicEntropy" HediffDef
HediffDefOf --> "PsychicHangover" HediffDef
HediffDefOf --> "PsychicSuppression" HediffDef
HediffDefOf --> "Abasia" HediffDef
HediffDefOf --> "PsychicLove" HediffDef
HediffDefOf --> "Flu" HediffDef
HediffDefOf --> "Plague" HediffDef
HediffDefOf --> "Malaria" HediffDef
HediffDefOf --> "WoundInfection" HediffDef
HediffDefOf --> "AlcoholHigh" HediffDef
HediffDefOf --> "Hangover" HediffDef
HediffDefOf --> "DrugOverdose" HediffDef
HediffDefOf --> "GoJuiceHigh" HediffDef
HediffDefOf --> "WakeUpTolerance" HediffDef
HediffDefOf --> "GoJuiceTolerance" HediffDef
HediffDefOf --> "BadBack" HediffDef
HediffDefOf --> "Cataract" HediffDef
HediffDefOf --> "Blindness" HediffDef
HediffDefOf --> "Frail" HediffDef
HediffDefOf --> "Carcinoma" HediffDef
HediffDefOf --> "Asthma" HediffDef
HediffDefOf --> "Dementia" HediffDef
HediffDefOf --> "PegLeg" HediffDef
HediffDefOf --> "Denture" HediffDef
HediffDefOf --> "SimpleProstheticLeg" HediffDef
HediffDefOf --> "SimpleProstheticArm" HediffDef
HediffDefOf --> "BionicEye" HediffDef
HediffDefOf --> "BionicArm" HediffDef
HediffDefOf --> "BionicLeg" HediffDef
HediffDefOf --> "PowerClaw" HediffDef
HediffDefOf --> "ArchotechEye" HediffDef
HediffDefOf --> "LoveEnhancer" HediffDef
HediffDefOf --> "NuclearStomach" HediffDef
HediffDefOf --> "PsychicAmplifier" HediffDef
HediffDefOf --> "PsychicHarmonizer" HediffDef
@enduml
