@startuml
class HediffCompProperties_RoyalImplant {
    + violationTriggerDescriptionKey : string
    + HediffCompProperties_RoyalImplant()
}
HediffCompProperties <|-- HediffCompProperties_RoyalImplant
@enduml
