@startuml
interface IInspectPane {
    RecentHeight : float <<get>> <<set>>
    AnythingSelected : bool <<get>>
    ShouldShowSelectNextInCellButton : bool <<get>>
    ShouldShowPaneContents : bool <<get>>
    PaneTopY : float <<get>>
    DrawInspectGizmos() : void
    GetLabel(rect:Rect) : string
    DoInspectPaneButtons(rect:Rect, lineEndWidth:float) : void
    SelectNextInCell() : void
    DoPaneContents(rect:Rect) : void
    CloseOpenTab() : void
    Reset() : void
}
class "IEnumerable`1"<T> {
}
IInspectPane --> "OpenTabType" Type
IInspectPane --> "CurTabs<InspectTabBase>" "IEnumerable`1"
@enduml
