@startuml
class InteractionWorker_RecruitAttempt {
    + <<const>> WildmanWildness : float = 0.75f
    + <<override>> Interacted(initiator:Pawn, recipient:Pawn, extraSentencePacks:List<RulePackDef>, letterText:string, letterLabel:string, letterDef:LetterDef, lookTargets:LookTargets) : void
    + {static} DoRecruit(recruiter:Pawn, recruitee:Pawn, recruitChance:float, useAudiovisualEffects:bool) : void
    + {static} DoRecruit(recruiter:Pawn, recruitee:Pawn, recruitChance:float, letterLabel:string, letter:string, useAudiovisualEffects:bool, sendLetter:bool) : void
}
InteractionWorker <|-- InteractionWorker_RecruitAttempt
@enduml
