@startuml
abstract class JobDriver_RemoveBuilding {
    + <<override>> ExposeData() : void
    + <<override>> TryMakePreToilReservations(errorOnFailed:bool) : bool
}
JobDriver <|-- JobDriver_RemoveBuilding
@enduml
