@startuml
class JobDefOf <<static>> {
    {static} JobDefOf()
}
JobDefOf --> "Goto" JobDef
JobDefOf --> "Wait" JobDef
JobDefOf --> "Wait_MaintainPosture" JobDef
JobDefOf --> "Wait_Downed" JobDef
JobDefOf --> "GotoWander" JobDef
JobDefOf --> "Wait_Wander" JobDef
JobDefOf --> "GotoSafeTemperature" JobDef
JobDefOf --> "Wait_SafeTemperature" JobDef
JobDefOf --> "Wait_Combat" JobDef
JobDefOf --> "Equip" JobDef
JobDefOf --> "AttackMelee" JobDef
JobDefOf --> "AttackStatic" JobDef
JobDefOf --> "UseVerbOnThing" JobDef
JobDefOf --> "UseVerbOnThingStatic" JobDef
JobDefOf --> "CastJump" JobDef
JobDefOf --> "CastAbilityOnThing" JobDef
JobDefOf --> "CastAbilityOnWorldTile" JobDef
JobDefOf --> "TakeInventory" JobDef
JobDefOf --> "Follow" JobDef
JobDefOf --> "FollowClose" JobDef
JobDefOf --> "Wear" JobDef
JobDefOf --> "RemoveApparel" JobDef
JobDefOf --> "DropEquipment" JobDef
JobDefOf --> "Strip" JobDef
JobDefOf --> "Open" JobDef
JobDefOf --> "Hunt" JobDef
JobDefOf --> "ManTurret" JobDef
JobDefOf --> "EnterCryptosleepCasket" JobDef
JobDefOf --> "UseNeurotrainer" JobDef
JobDefOf --> "UseArtifact" JobDef
JobDefOf --> "TriggerFirefoamPopper" JobDef
JobDefOf --> "ClearSnow" JobDef
JobDefOf --> "Vomit" JobDef
JobDefOf --> "Flick" JobDef
JobDefOf --> "DoBill" JobDef
JobDefOf --> "Research" JobDef
JobDefOf --> "Mine" JobDef
JobDefOf --> "OperateDeepDrill" JobDef
JobDefOf --> "OperateScanner" JobDef
JobDefOf --> "Repair" JobDef
JobDefOf --> "FixBrokenDownBuilding" JobDef
JobDefOf --> "UseCommsConsole" JobDef
JobDefOf --> "Clean" JobDef
JobDefOf --> "TradeWithPawn" JobDef
JobDefOf --> "Flee" JobDef
JobDefOf --> "FleeAndCower" JobDef
JobDefOf --> "Lovin" JobDef
JobDefOf --> "SocialFight" JobDef
JobDefOf --> "Maintain" JobDef
JobDefOf --> "GiveToPackAnimal" JobDef
JobDefOf --> "EnterTransporter" JobDef
JobDefOf --> "Resurrect" JobDef
JobDefOf --> "Insult" JobDef
JobDefOf --> "HaulCorpseToPublicPlace" JobDef
JobDefOf --> "InducePrisonerToEscape" JobDef
JobDefOf --> "OfferHelp" JobDef
JobDefOf --> "ApplyTechprint" JobDef
JobDefOf --> "GotoMindControlled" JobDef
JobDefOf --> "MarryAdjacentPawn" JobDef
JobDefOf --> "SpectateCeremony" JobDef
JobDefOf --> "StandAndBeSociallyActive" JobDef
JobDefOf --> "GiveSpeech" JobDef
JobDefOf --> "PrepareCaravan_GatherItems" JobDef
JobDefOf --> "PrepareCaravan_GatherPawns" JobDef
JobDefOf --> "PrepareCaravan_GatherDownedPawns" JobDef
JobDefOf --> "Ignite" JobDef
JobDefOf --> "BeatFire" JobDef
JobDefOf --> "ExtinguishSelf" JobDef
JobDefOf --> "LayDown" JobDef
JobDefOf --> "Ingest" JobDef
JobDefOf --> "SocialRelax" JobDef
JobDefOf --> "HaulToCell" JobDef
JobDefOf --> "HaulToContainer" JobDef
JobDefOf --> "Steal" JobDef
JobDefOf --> "Reload" JobDef
JobDefOf --> "Refuel" JobDef
JobDefOf --> "RefuelAtomic" JobDef
JobDefOf --> "RearmTurret" JobDef
JobDefOf --> "RearmTurretAtomic" JobDef
JobDefOf --> "FillFermentingBarrel" JobDef
JobDefOf --> "TakeBeerOutOfFermentingBarrel" JobDef
JobDefOf --> "UnloadInventory" JobDef
JobDefOf --> "UnloadYourInventory" JobDef
JobDefOf --> "HaulToTransporter" JobDef
JobDefOf --> "Rescue" JobDef
JobDefOf --> "Arrest" JobDef
JobDefOf --> "Capture" JobDef
JobDefOf --> "TakeWoundedPrisonerToBed" JobDef
JobDefOf --> "TakeToBedToOperate" JobDef
JobDefOf --> "EscortPrisonerToBed" JobDef
JobDefOf --> "CarryToCryptosleepCasket" JobDef
JobDefOf --> "ReleasePrisoner" JobDef
JobDefOf --> "Kidnap" JobDef
JobDefOf --> "CarryDownedPawnToExit" JobDef
JobDefOf --> "PlaceNoCostFrame" JobDef
JobDefOf --> "FinishFrame" JobDef
JobDefOf --> "Deconstruct" JobDef
JobDefOf --> "Uninstall" JobDef
JobDefOf --> "SmoothFloor" JobDef
JobDefOf --> "RemoveFloor" JobDef
JobDefOf --> "BuildRoof" JobDef
JobDefOf --> "RemoveRoof" JobDef
JobDefOf --> "SmoothWall" JobDef
JobDefOf --> "PrisonerAttemptRecruit" JobDef
JobDefOf --> "PrisonerExecution" JobDef
JobDefOf --> "DeliverFood" JobDef
JobDefOf --> "FeedPatient" JobDef
JobDefOf --> "TendPatient" JobDef
JobDefOf --> "VisitSickPawn" JobDef
JobDefOf --> "Sow" JobDef
JobDefOf --> "Harvest" JobDef
JobDefOf --> "CutPlant" JobDef
JobDefOf --> "HarvestDesignated" JobDef
JobDefOf --> "CutPlantDesignated" JobDef
JobDefOf --> "Slaughter" JobDef
JobDefOf --> "Milk" JobDef
JobDefOf --> "Shear" JobDef
JobDefOf --> "Tame" JobDef
JobDefOf --> "Train" JobDef
JobDefOf --> "Nuzzle" JobDef
JobDefOf --> "Mate" JobDef
JobDefOf --> "LayEgg" JobDef
JobDefOf --> "PredatorHunt" JobDef
JobDefOf --> "Reign" JobDef
JobDefOf --> "Meditate" JobDef
JobDefOf --> "Play_MusicalInstrument" JobDef
JobDefOf --> "LinkPsylinkable" JobDef
JobDefOf --> "BestowingCeremony" JobDef
@enduml
