@startuml
class JobDriver_UnloadYourInventory {
    + <<override>> ExposeData() : void
    + <<override>> TryMakePreToilReservations(errorOnFailed:bool) : bool
}
JobDriver <|-- JobDriver_UnloadYourInventory
@enduml
