@startuml
class JobDriver_TendPatient {
    + <<override>> ExposeData() : void
    + <<override>> Notify_Starting() : void
    + <<override>> TryMakePreToilReservations(errorOnFailed:bool) : bool
    + <<override>> Notify_DamageTaken(dinfo:DamageInfo) : void
}
JobDriver <|-- JobDriver_TendPatient
@enduml
