@startuml
class JoyGiver_SocialRelax {
    + <<override>> TryGiveJob(pawn:Pawn) : Job
    + <<override>> TryGiveJobInGatheringArea(pawn:Pawn, gatheringSpot:IntVec3) : Job
}
JoyGiver <|-- JoyGiver_SocialRelax
@enduml
