@startuml
class KeyBindingDefOf <<static>> {
    {static} KeyBindingDefOf()
}
KeyBindingDefOf --> "MapDolly_Up" KeyBindingDef
KeyBindingDefOf --> "MapDolly_Down" KeyBindingDef
KeyBindingDefOf --> "MapDolly_Left" KeyBindingDef
KeyBindingDefOf --> "MapDolly_Right" KeyBindingDef
KeyBindingDefOf --> "MapZoom_In" KeyBindingDef
KeyBindingDefOf --> "MapZoom_Out" KeyBindingDef
KeyBindingDefOf --> "Accept" KeyBindingDef
KeyBindingDefOf --> "Cancel" KeyBindingDef
KeyBindingDefOf --> "ToggleScreenshotMode" KeyBindingDef
KeyBindingDefOf --> "TakeScreenshot" KeyBindingDef
KeyBindingDefOf --> "SelectNextInCell" KeyBindingDef
KeyBindingDefOf --> "TogglePause" KeyBindingDef
KeyBindingDefOf --> "TimeSpeed_Normal" KeyBindingDef
KeyBindingDefOf --> "TimeSpeed_Fast" KeyBindingDef
KeyBindingDefOf --> "TimeSpeed_Superfast" KeyBindingDef
KeyBindingDefOf --> "TimeSpeed_Ultrafast" KeyBindingDef
KeyBindingDefOf --> "PreviousColonist" KeyBindingDef
KeyBindingDefOf --> "NextColonist" KeyBindingDef
KeyBindingDefOf --> "ToggleBeautyDisplay" KeyBindingDef
KeyBindingDefOf --> "ToggleRoomStatsDisplay" KeyBindingDef
KeyBindingDefOf --> "QueueOrder" KeyBindingDef
KeyBindingDefOf --> "Misc1" KeyBindingDef
KeyBindingDefOf --> "Misc2" KeyBindingDef
KeyBindingDefOf --> "Misc3" KeyBindingDef
KeyBindingDefOf --> "Misc4" KeyBindingDef
KeyBindingDefOf --> "Misc5" KeyBindingDef
KeyBindingDefOf --> "Misc6" KeyBindingDef
KeyBindingDefOf --> "Misc7" KeyBindingDef
KeyBindingDefOf --> "Misc8" KeyBindingDef
KeyBindingDefOf --> "Misc9" KeyBindingDef
KeyBindingDefOf --> "Misc10" KeyBindingDef
KeyBindingDefOf --> "Misc11" KeyBindingDef
KeyBindingDefOf --> "Misc12" KeyBindingDef
KeyBindingDefOf --> "Command_TogglePower" KeyBindingDef
KeyBindingDefOf --> "Command_ItemForbid" KeyBindingDef
KeyBindingDefOf --> "Command_ColonistDraft" KeyBindingDef
KeyBindingDefOf --> "ModifierIncrement_10x" KeyBindingDef
KeyBindingDefOf --> "ModifierIncrement_100x" KeyBindingDef
KeyBindingDefOf --> "Designator_Cancel" KeyBindingDef
KeyBindingDefOf --> "Designator_Deconstruct" KeyBindingDef
KeyBindingDefOf --> "Designator_RotateLeft" KeyBindingDef
KeyBindingDefOf --> "Designator_RotateRight" KeyBindingDef
KeyBindingDefOf --> "Dev_TickOnce" KeyBindingDef
KeyBindingDefOf --> "Dev_ToggleGodMode" KeyBindingDef
KeyBindingDefOf --> "Dev_ToggleDebugLog" KeyBindingDef
KeyBindingDefOf --> "Dev_ToggleDebugActionsMenu" KeyBindingDef
KeyBindingDefOf --> "Dev_ChangeSelectedDebugAction" KeyBindingDef
KeyBindingDefOf --> "Dev_ToggleDebugLogMenu" KeyBindingDef
KeyBindingDefOf --> "Dev_ToggleDebugInspector" KeyBindingDef
KeyBindingDefOf --> "Dev_ToggleDebugSettingsMenu" KeyBindingDef
@enduml
