@startuml
enum KnowledgeAmount {
    None,
    FrameDisplayed,
    FrameInteraction,
    TinyInteraction,
    SmallInteraction,
    SpecificInteraction,
    Total,
    NoteClosed,
    NoteTaught,
}
@enduml
