@startuml
class Listing_ResourceReadout {
    + Listing_ResourceReadout(map:Map)
    + DoCategory(node:TreeNode_ThingCategory, nestLevel:int, openMask:int) : void
    + DoCategoryChildren(node:TreeNode_ThingCategory, indentLevel:int, openMask:int) : void
}
Listing_Tree <|-- Listing_ResourceReadout
@enduml
