@startuml
class ListerHaulables {
    + ListerHaulables(map:Map)
    + ThingsPotentiallyNeedingHauling() : List<Thing>
    + Notify_Spawned(t:Thing) : void
    + Notify_DeSpawned(t:Thing) : void
    + HaulDesignationAdded(t:Thing) : void
    + HaulDesignationRemoved(t:Thing) : void
    + Notify_Unforbidden(t:Thing) : void
    + Notify_Forbidden(t:Thing) : void
    + Notify_SlotGroupChanged(sg:SlotGroup) : void
    + ListerHaulablesTick() : void
    + RecalcAllInCell(c:IntVec3) : void
    + RecalcAllInCells(cells:IEnumerable<IntVec3>) : void
}
@enduml
