@startuml
class OutfitDatabase <<sealed>> {
    + OutfitDatabase()
    + ExposeData() : void
    + DefaultOutfit() : Outfit
    + TryDelete(outfit:Outfit) : AcceptanceReport
    + MakeNewOutfit() : Outfit
}
class "List`1"<T> {
}
IExposable <|-- OutfitDatabase
OutfitDatabase --> "AllOutfits<Outfit>" "List`1"
@enduml
