@startuml
class PawnCapacityWorker_Talking {
    + <<override>> CalculateCapacityLevel(diffSet:HediffSet, impactors:List<PawnCapacityUtility.CapacityImpactor>) : float
    + <<override>> CanHaveCapacity(body:BodyDef) : bool
}
PawnCapacityWorker <|-- PawnCapacityWorker_Talking
@enduml
