@startuml
class PawnCapacityWorker_Eating {
    + <<override>> CalculateCapacityLevel(diffSet:HediffSet, impactors:List<PawnCapacityUtility.CapacityImpactor>) : float
    + <<override>> CanHaveCapacity(body:BodyDef) : bool
}
PawnCapacityWorker <|-- PawnCapacityWorker_Eating
@enduml
