@startuml
class PawnGroupKindWorker_Normal {
    + <<override>> MinPointsToGenerateAnything(groupMaker:PawnGroupMaker) : float
    + <<override>> CanGenerateFrom(parms:PawnGroupMakerParms, groupMaker:PawnGroupMaker) : bool
    + <<override>> GeneratePawnKindsExample(parms:PawnGroupMakerParms, groupMaker:PawnGroupMaker) : IEnumerable<PawnKindDef>
}
PawnGroupKindWorker <|-- PawnGroupKindWorker_Normal
@enduml
