@startuml
class PawnCapacityWorker_Consciousness {
    + <<override>> CalculateCapacityLevel(diffSet:HediffSet, impactors:List<PawnCapacityUtility.CapacityImpactor>) : float
    + <<override>> CanHaveCapacity(body:BodyDef) : bool
}
PawnCapacityWorker <|-- PawnCapacityWorker_Consciousness
@enduml
