@startuml
class PawnRelationWorker_ExSpouse {
    + <<override>> GenerationChance(generated:Pawn, other:Pawn, request:PawnGenerationRequest) : float
    + <<override>> CreateRelation(generated:Pawn, other:Pawn, request:PawnGenerationRequest) : void
}
PawnRelationWorker <|-- PawnRelationWorker_ExSpouse
@enduml
