@startuml
class PawnRelationWorker_Parent {
    + <<override>> GenerationChance(generated:Pawn, other:Pawn, request:PawnGenerationRequest) : float
    + <<override>> CreateRelation(generated:Pawn, other:Pawn, request:PawnGenerationRequest) : void
}
PawnRelationWorker <|-- PawnRelationWorker_Parent
@enduml
