@startuml
class PawnsArrivalModeWorker_CenterDrop {
    + <<const>> PodOpenDelay : int = 520
    + <<override>> Arrive(pawns:List<Pawn>, parms:IncidentParms) : void
    + <<override>> TravelingTransportPodsArrived(dropPods:List<ActiveDropPodInfo>, map:Map) : void
    + <<override>> TryResolveRaidSpawnCenter(parms:IncidentParms) : bool
}
PawnsArrivalModeWorker <|-- PawnsArrivalModeWorker_CenterDrop
@enduml
