@startuml
class PawnsArrivalModeWorker_ClusterDrop {
    + <<override>> Arrive(pawns:List<Pawn>, parms:IncidentParms) : void
    + <<override>> TravelingTransportPodsArrived(dropPods:List<ActiveDropPodInfo>, map:Map) : void
    + <<override>> TryResolveRaidSpawnCenter(parms:IncidentParms) : bool
}
PawnsArrivalModeWorker <|-- PawnsArrivalModeWorker_ClusterDrop
@enduml
