@startuml
class PawnsArrivalModeWorker_EdgeWalkInGroups {
    + <<override>> Arrive(pawns:List<Pawn>, parms:IncidentParms) : void
    + <<override>> TryResolveRaidSpawnCenter(parms:IncidentParms) : bool
}
PawnsArrivalModeWorker <|-- PawnsArrivalModeWorker_EdgeWalkInGroups
@enduml
