@startuml
class PawnsArrivalModeWorker_EdgeDropGroups {
    + <<override>> Arrive(pawns:List<Pawn>, parms:IncidentParms) : void
    + <<override>> TryResolveRaidSpawnCenter(parms:IncidentParms) : bool
}
PawnsArrivalModeWorker <|-- PawnsArrivalModeWorker_EdgeDropGroups
@enduml
