@startuml
class PawnColumnWorker_Trainable {
    + <<override>> DoHeader(rect:Rect, table:PawnTable) : void
    + <<override>> DoCell(rect:Rect, pawn:Pawn, table:PawnTable) : void
    + <<override>> GetMinWidth(table:PawnTable) : int
    + <<override>> GetMaxWidth(table:PawnTable) : int
    + <<override>> GetMinCellHeight(pawn:Pawn) : int
    + <<override>> Compare(a:Pawn, b:Pawn) : int
}
PawnColumnWorker <|-- PawnColumnWorker_Trainable
@enduml
