@startuml
class PlaceWorker_MeditationOffsetBuildingsNear {
    + <<override>> DrawGhost(def:ThingDef, center:IntVec3, rot:Rot4, ghostCol:Color, thing:Thing) : void
}
PlaceWorker <|-- PlaceWorker_MeditationOffsetBuildingsNear
PlaceWorker_MeditationOffsetBuildingsNear o-> "RingColor" Color
@enduml
