@startuml
class PlaceWorker_NeverAdjacentTrap {
    + <<override>> DrawGhost(def:ThingDef, center:IntVec3, rot:Rot4, ghostCol:Color, thing:Thing) : void
    + <<override>> AllowsPlacing(def:BuildableDef, center:IntVec3, rot:Rot4, map:Map, thingToIgnore:Thing, thing:Thing) : AcceptanceReport
}
PlaceWorker <|-- PlaceWorker_NeverAdjacentTrap
@enduml
