@startuml
class PlaceWorker_ShowInstrumentAoE {
    + <<override>> AllowsPlacing(checkingDef:BuildableDef, loc:IntVec3, rot:Rot4, map:Map, thingToIgnore:Thing, thing:Thing) : AcceptanceReport
}
PlaceWorker <|-- PlaceWorker_ShowInstrumentAoE
@enduml
