@startuml
class PlaceWorker_NextToHopperAccepter {
    + <<override>> AllowsPlacing(checkingDef:BuildableDef, loc:IntVec3, rot:Rot4, map:Map, thingToIgnore:Thing, thing:Thing) : AcceptanceReport
}
PlaceWorker <|-- PlaceWorker_NextToHopperAccepter
@enduml
