@startuml
class PlaceWorker_ShowTradeBeaconRadius {
    + <<override>> DrawGhost(def:ThingDef, center:IntVec3, rot:Rot4, ghostCol:Color, thing:Thing) : void
}
PlaceWorker <|-- PlaceWorker_ShowTradeBeaconRadius
@enduml
