@startuml
class PortraitCameraManager <<static>> {
    {static} PortraitCameraManager()
}
PortraitCameraManager --> "PortraitCamera" Camera
PortraitCameraManager --> "PortraitRenderer" PortraitRenderer
@enduml
