@startuml
class PowerOverlayMats <<static>> {
    {static} PowerOverlayMats()
}
PowerOverlayMats --> "LinkedOverlayGraphic" Graphic
PowerOverlayMats --> "MatConnectorBase" Material
PowerOverlayMats --> "MatConnectorLine" Material
PowerOverlayMats --> "MatConnectorAnticipated" Material
PowerOverlayMats --> "MatConnectorBaseAnticipated" Material
@enduml
