@startuml
class QuestPart_PassAnyOutMany {
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
}
class "List`1"<T> {
}
QuestPart <|-- QuestPart_PassAnyOutMany
QuestPart_PassAnyOutMany o-> "inSignals<string>" "List`1"
QuestPart_PassAnyOutMany o-> "outSignals<string>" "List`1"
@enduml
