@startuml
class QuestPart_Leave {
    + inSignal : string
    + sendStandardLetter : bool = true
    + leaveOnCleanup : bool = true
    + inSignalRemovePawn : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> Cleanup() : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
    + <<override>> ReplacePawnReferences(replace:Pawn, with:Pawn) : void
}
class "List`1"<T> {
}
class "IEnumerable`1"<T> {
}
QuestPart <|-- QuestPart_Leave
QuestPart_Leave o-> "pawns<Pawn>" "List`1"
QuestPart_Leave --> "QuestLookTargets<GlobalTargetInfo>" "IEnumerable`1"
@enduml
