@startuml
class QuestPart_Filter_AllPawnsDowned {
    + inSignalRemovePawn : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
}
class "List`1"<T> {
}
QuestPart_Filter <|-- QuestPart_Filter_AllPawnsDowned
QuestPart_Filter_AllPawnsDowned --> "pawns<Pawn>" "List`1"
@enduml
