@startuml
class QuestPart_Filter_AllPawnsDestroyed {
    + inSignalRemovePawn : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
}
class "List`1"<T> {
}
QuestPart_Filter <|-- QuestPart_Filter_AllPawnsDestroyed
QuestPart_Filter_AllPawnsDestroyed --> "pawns<Pawn>" "List`1"
@enduml
