@startuml
abstract class QuestPart_Filter {
    + inSignal : string
    + outSignal : string
    + outSignalElse : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
}
QuestPart <|-- QuestPart_Filter
@enduml
