@startuml
class QuestPart_ExtraFaction {
    + areHelpers : bool
    + inSignalRemovePawn : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> QuestPartReserves(f:Faction) : bool
    + <<override>> ExposeData() : void
    + <<override>> ReplacePawnReferences(replace:Pawn, with:Pawn) : void
    + <<override>> Cleanup() : void
    + <<override>> Notify_FactionRemoved(faction:Faction) : void
}
class "List`1"<T> {
}
class "IEnumerable`1"<T> {
}
QuestPartActivable <|-- QuestPart_ExtraFaction
QuestPart_ExtraFaction --> "extraFaction" ExtraFaction
QuestPart_ExtraFaction o-> "affectedPawns<Pawn>" "List`1"
QuestPart_ExtraFaction --> "InvolvedFactions<Faction>" "IEnumerable`1"
@enduml
