@startuml
class QuestPart_BiocodeWeapons {
    + inSignal : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> ReplacePawnReferences(replace:Pawn, with:Pawn) : void
}
class "List`1"<T> {
}
QuestPart <|-- QuestPart_BiocodeWeapons
QuestPart_BiocodeWeapons o-> "pawns<Pawn>" "List`1"
@enduml
