@startuml
class QuestPart_SendShuttleAway {
    + inSignal : string
    + dropEverything : bool
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
    + <<override>> ReplacePawnReferences(replace:Pawn, with:Pawn) : void
}
class "IEnumerable`1"<T> {
}
QuestPart <|-- QuestPart_SendShuttleAway
QuestPart_SendShuttleAway --> "shuttle" Thing
QuestPart_SendShuttleAway --> "QuestLookTargets<GlobalTargetInfo>" "IEnumerable`1"
@enduml
