@startuml
class QuestPart_PassAllSequence {
    + outSignal : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
}
class "List`1"<T> {
}
QuestPart <|-- QuestPart_PassAllSequence
QuestPart_PassAllSequence o-> "inSignals<string>" "List`1"
@enduml
