@startuml
class QuestPart_PassOutRandom {
    + inSignal : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
}
class "List`1"<T> {
}
QuestPart <|-- QuestPart_PassOutRandom
QuestPart_PassOutRandom o-> "outSignals<string>" "List`1"
@enduml
