@startuml
class QuestPart_IsDead {
    + <<override>> QuestPartTick() : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
    + <<override>> ReplacePawnReferences(replace:Pawn, with:Pawn) : void
}
class "IEnumerable`1"<T> {
}
QuestPartActivable <|-- QuestPart_IsDead
QuestPart_IsDead --> "pawn" Pawn
QuestPart_IsDead --> "QuestLookTargets<GlobalTargetInfo>" "IEnumerable`1"
@enduml
