@startuml
class QuestPart_Log {
    + inSignal : string
    + message : string
    + <<override>> Notify_QuestSignalReceived(signal:Signal) : void
    + <<override>> ExposeData() : void
    + <<override>> AssignDebugData() : void
}
QuestPart <|-- QuestPart_Log
@enduml
