@startuml
class RaidStrategyDefOf <<static>> {
    {static} RaidStrategyDefOf()
}
RaidStrategyDefOf --> "ImmediateAttack" RaidStrategyDef
RaidStrategyDefOf --> "ImmediateAttackFriendly" RaidStrategyDef
@enduml
