@startuml
class RaidStrategyWorker_ImmediateAttackFriendly {
    + <<override>> CanUseWith(parms:IncidentParms, groupKind:PawnGroupKindDef) : bool
}
RaidStrategyWorker_ImmediateAttack <|-- RaidStrategyWorker_ImmediateAttackFriendly
@enduml
