@startuml
class RecordDefOf <<static>> {
    {static} RecordDefOf()
}
RecordDefOf --> "Kills" RecordDef
RecordDefOf --> "KillsHumanlikes" RecordDef
RecordDefOf --> "KillsAnimals" RecordDef
RecordDefOf --> "KillsMechanoids" RecordDef
RecordDefOf --> "PawnsDowned" RecordDef
RecordDefOf --> "PawnsDownedHumanlikes" RecordDef
RecordDefOf --> "PawnsDownedAnimals" RecordDef
RecordDefOf --> "PawnsDownedMechanoids" RecordDef
RecordDefOf --> "ShotsFired" RecordDef
RecordDefOf --> "Headshots" RecordDef
RecordDefOf --> "DamageDealt" RecordDef
RecordDefOf --> "DamageTaken" RecordDef
RecordDefOf --> "TimesInMentalState" RecordDef
RecordDefOf --> "TimesOnFire" RecordDef
RecordDefOf --> "FiresExtinguished" RecordDef
RecordDefOf --> "OperationsReceived" RecordDef
RecordDefOf --> "OperationsPerformed" RecordDef
RecordDefOf --> "TimesTendedTo" RecordDef
RecordDefOf --> "TimesTendedOther" RecordDef
RecordDefOf --> "PeopleCaptured" RecordDef
RecordDefOf --> "PrisonersRecruited" RecordDef
RecordDefOf --> "PrisonersChatted" RecordDef
RecordDefOf --> "AnimalsTamed" RecordDef
RecordDefOf --> "AnimalsSlaughtered" RecordDef
RecordDefOf --> "MealsCooked" RecordDef
RecordDefOf --> "ThingsConstructed" RecordDef
RecordDefOf --> "ThingsInstalled" RecordDef
RecordDefOf --> "ThingsRepaired" RecordDef
RecordDefOf --> "ThingsCrafted" RecordDef
RecordDefOf --> "ThingsHauled" RecordDef
RecordDefOf --> "PlantsSown" RecordDef
RecordDefOf --> "PlantsHarvested" RecordDef
RecordDefOf --> "CellsMined" RecordDef
RecordDefOf --> "MessesCleaned" RecordDef
RecordDefOf --> "ResearchPointsResearched" RecordDef
RecordDefOf --> "CorpsesBuried" RecordDef
RecordDefOf --> "NutritionEaten" RecordDef
RecordDefOf --> "BodiesStripped" RecordDef
RecordDefOf --> "ThingsUninstalled" RecordDef
RecordDefOf --> "ThingsDeconstructed" RecordDef
RecordDefOf --> "ArtifactsActivated" RecordDef
RecordDefOf --> "ContainersOpened" RecordDef
RecordDefOf --> "SwitchesFlicked" RecordDef
RecordDefOf --> "TimeAsColonistOrColonyAnimal" RecordDef
RecordDefOf --> "TimeAsPrisoner" RecordDef
RecordDefOf --> "TimeAsQuestLodger" RecordDef
@enduml
