@startuml
class RoomRequirement_TerrainWithTags {
    + <<override>> Met(r:Room, p:Pawn) : bool
    + <<override>> SameOrSubsetOf(other:RoomRequirement) : bool
    + <<override>> ConfigErrors() : IEnumerable<string>
}
class "List`1"<T> {
}
RoomRequirement <|-- RoomRequirement_TerrainWithTags
RoomRequirement_TerrainWithTags --> "tags<string>" "List`1"
@enduml
