@startuml
class RoomRequirement_Impressiveness {
    + impressiveness : int
    + <<override>> Label(r:Room) : string
    + <<override>> Met(r:Room, p:Pawn) : bool
    + <<override>> ConfigErrors() : IEnumerable<string>
}
RoomRequirement <|-- RoomRequirement_Impressiveness
@enduml
