@startuml
class RulePackDefOf <<static>> {
    {static} RulePackDefOf()
}
RulePackDefOf --> "Sentence_SocialFightStarted" RulePackDef
RulePackDefOf --> "Sentence_RomanceAttemptAccepted" RulePackDef
RulePackDefOf --> "Sentence_RomanceAttemptRejected" RulePackDef
RulePackDefOf --> "Sentence_MarriageProposalAccepted" RulePackDef
RulePackDefOf --> "Sentence_MarriageProposalRejected" RulePackDef
RulePackDefOf --> "Sentence_MarriageProposalRejectedBrokeUp" RulePackDef
RulePackDefOf --> "Sentence_RecruitAttemptAccepted" RulePackDef
RulePackDefOf --> "Sentence_RecruitAttemptRejected" RulePackDef
RulePackDefOf --> "ArtDescriptionRoot_HasTale" RulePackDef
RulePackDefOf --> "ArtDescriptionRoot_Taleless" RulePackDef
RulePackDefOf --> "ArtDescriptionUtility_Global" RulePackDef
RulePackDefOf --> "GlobalUtility" RulePackDef
RulePackDefOf --> "TalelessImages" RulePackDef
RulePackDefOf --> "NamerWorld" RulePackDef
RulePackDefOf --> "NamerTraderGeneral" RulePackDef
RulePackDefOf --> "NamerScenario" RulePackDef
RulePackDefOf --> "NamerQuestDefault" RulePackDef
RulePackDefOf --> "NamerArtSculpture" RulePackDef
RulePackDefOf --> "ArtDescription_Sculpture" RulePackDef
RulePackDefOf --> "NamerArtWeaponMelee" RulePackDef
RulePackDefOf --> "ArtDescription_WeaponMelee" RulePackDef
RulePackDefOf --> "NamerArtWeaponGun" RulePackDef
RulePackDefOf --> "ArtDescription_WeaponGun" RulePackDef
RulePackDefOf --> "NamerArtFurniture" RulePackDef
RulePackDefOf --> "ArtDescription_Furniture" RulePackDef
RulePackDefOf --> "NamerArtSarcophagusPlate" RulePackDef
RulePackDefOf --> "ArtDescription_SarcophagusPlate" RulePackDef
RulePackDefOf --> "SeedGenerator" RulePackDef
RulePackDefOf --> "GameplayTips" RulePackDef
RulePackDefOf --> "Combat_RangedFire" RulePackDef
RulePackDefOf --> "Combat_RangedDamage" RulePackDef
RulePackDefOf --> "Combat_RangedDeflect" RulePackDef
RulePackDefOf --> "Combat_RangedMiss" RulePackDef
RulePackDefOf --> "Combat_ExplosionImpact" RulePackDef
RulePackDefOf --> "Transition_Downed" RulePackDef
RulePackDefOf --> "Transition_Died" RulePackDef
RulePackDefOf --> "Transition_DiedExplosive" RulePackDef
RulePackDefOf --> "DamageEvent_Ceiling" RulePackDef
RulePackDefOf --> "DamageEvent_Fire" RulePackDef
RulePackDefOf --> "DamageEvent_PowerBeam" RulePackDef
RulePackDefOf --> "DamageEvent_Tornado" RulePackDef
RulePackDefOf --> "DamageEvent_TrapSpike" RulePackDef
RulePackDefOf --> "Event_Stun" RulePackDef
RulePackDefOf --> "Event_AbilityUsed" RulePackDef
RulePackDefOf --> "Event_ItemUsed" RulePackDef
RulePackDefOf --> "Battle_Solo" RulePackDef
RulePackDefOf --> "Battle_Duel" RulePackDef
RulePackDefOf --> "Battle_Internal" RulePackDef
RulePackDefOf --> "Battle_War" RulePackDef
RulePackDefOf --> "Battle_Brawl" RulePackDef
RulePackDefOf --> "DynamicWrapper" RulePackDef
@enduml
