@startuml
enum ScenPartCategory {
    Undefined,
    Fixed,
    StartingImportant,
    PlayerPawnFilter,
    PlayerPawnModifier,
    GameCondition,
    Rule,
    StartingItem,
    WorldThing,
    Misc,
}
@enduml
