@startuml
class ScenPart_DisallowBuilding {
    + <<override>> Summary(scen:Scenario) : string
    + <<override>> GetSummaryListEntries(tag:string) : IEnumerable<string>
    + <<override>> ExposeData() : void
    + <<override>> Randomize() : void
    + <<override>> DoEditInterface(listing:Listing_ScenEdit) : void
    + <<override>> TryMerge(other:ScenPart) : bool
}
ScenPart_Rule <|-- ScenPart_DisallowBuilding
@enduml
