@startuml
class ScenPart_SetNeedLevel {
    + <<override>> DoEditInterface(listing:Listing_ScenEdit) : void
    + <<override>> ExposeData() : void
    + <<override>> Summary(scen:Scenario) : string
    + <<override>> Randomize() : void
    + <<override>> TryMerge(other:ScenPart) : bool
}
ScenPart_PawnModifier <|-- ScenPart_SetNeedLevel
@enduml
