@startuml
class ScenPart_StartingAnimal {
    + <<override>> ExposeData() : void
    + <<override>> DoEditInterface(listing:Listing_ScenEdit) : void
    + <<override>> Summary(scen:Scenario) : string
    + <<override>> GetSummaryListEntries(tag:string) : IEnumerable<string>
    + <<override>> Randomize() : void
    + <<override>> TryMerge(other:ScenPart) : bool
    + <<override>> PlayerStartingThings() : IEnumerable<Thing>
}
ScenPart <|-- ScenPart_StartingAnimal
@enduml
