@startuml
class SectionLayer_BridgeProps {
    + <<override>> Visible : bool <<get>>
    + SectionLayer_BridgeProps(section:Section)
    + <<override>> Regenerate() : void
}
SectionLayer <|-- SectionLayer_BridgeProps
@enduml
