@startuml
class Signal <<struct>> {
    + tag : string
    + Signal(tag:string)
    + Signal(tag:string, args:SignalArgs)
    + Signal(tag:string, arg1:NamedArgument)
    + Signal(tag:string, arg1:NamedArgument, arg2:NamedArgument)
    + Signal(tag:string, arg1:NamedArgument, arg2:NamedArgument, arg3:NamedArgument)
    + Signal(tag:string, arg1:NamedArgument, arg2:NamedArgument, arg3:NamedArgument, arg4:NamedArgument)
    + Signal(tag:string, args:NamedArgument[])
}
Signal --> "args" SignalArgs
@enduml
