@startuml
class SitePartWorker_ConditionCauser_PsychicSuppressor {
    + <<override>> Notify_GeneratedByQuestGen(part:SitePart, slate:Slate, outExtraDescriptionRules:List<Rule>, outExtraDescriptionConstants:Dictionary<string, string>) : void
}
SitePartWorker_ConditionCauser <|-- SitePartWorker_ConditionCauser_PsychicSuppressor
@enduml
