@startuml
class SitePartWorker_Manhunters {
    + <<override>> GetArrivedLetterPart(map:Map, preferredLetterDef:LetterDef, lookTargets:LookTargets) : string
    + <<override>> GenerateDefaultParams(myThreatPoints:float, tile:int, faction:Faction) : SitePartParams
    + <<override>> Notify_GeneratedByQuestGen(part:SitePart, slate:Slate, outExtraDescriptionRules:List<Rule>, outExtraDescriptionConstants:Dictionary<string, string>) : void
    + <<override>> GetPostProcessedThreatLabel(site:Site, sitePart:SitePart) : string
}
SitePartWorker <|-- SitePartWorker_Manhunters
@enduml
