@startuml
class SoundDefOf <<static>> {
    {static} SoundDefOf()
}
SoundDefOf --> "Tick_High" SoundDef
SoundDefOf --> "Tick_Low" SoundDef
SoundDefOf --> "Tick_Tiny" SoundDef
SoundDefOf --> "Crunch" SoundDef
SoundDefOf --> "Click" SoundDef
SoundDefOf --> "ClickReject" SoundDef
SoundDefOf --> "CancelMode" SoundDef
SoundDefOf --> "TabClose" SoundDef
SoundDefOf --> "TabOpen" SoundDef
SoundDefOf --> "Checkbox_TurnedOff" SoundDef
SoundDefOf --> "Checkbox_TurnedOn" SoundDef
SoundDefOf --> "RowTabSelect" SoundDef
SoundDefOf --> "ArchitectCategorySelect" SoundDef
SoundDefOf --> "ExecuteTrade" SoundDef
SoundDefOf --> "FloatMenu_Open" SoundDef
SoundDefOf --> "FloatMenu_Cancel" SoundDef
SoundDefOf --> "DialogBoxAppear" SoundDef
SoundDefOf --> "TutorMessageAppear" SoundDef
SoundDefOf --> "TinyBell" SoundDef
SoundDefOf --> "PageChange" SoundDef
SoundDefOf --> "DragSlider" SoundDef
SoundDefOf --> "Lesson_Activated" SoundDef
SoundDefOf --> "Lesson_Deactivated" SoundDef
SoundDefOf --> "DraftOn" SoundDef
SoundDefOf --> "DraftOff" SoundDef
SoundDefOf --> "CommsWindow_Open" SoundDef
SoundDefOf --> "CommsWindow_Close" SoundDef
SoundDefOf --> "RadioComms_Ambience" SoundDef
SoundDefOf --> "InfoCard_Open" SoundDef
SoundDefOf --> "InfoCard_Close" SoundDef
SoundDefOf --> "Clock_Stop" SoundDef
SoundDefOf --> "Clock_Normal" SoundDef
SoundDefOf --> "Clock_Fast" SoundDef
SoundDefOf --> "Clock_Superfast" SoundDef
SoundDefOf --> "Quest_Accepted" SoundDef
SoundDefOf --> "Quest_Succeded" SoundDef
SoundDefOf --> "Quest_Concluded" SoundDef
SoundDefOf --> "Quest_Failed" SoundDef
SoundDefOf --> "Mouseover_Standard" SoundDef
SoundDefOf --> "Mouseover_Thump" SoundDef
SoundDefOf --> "Mouseover_Category" SoundDef
SoundDefOf --> "Mouseover_Command" SoundDef
SoundDefOf --> "Mouseover_ButtonToggle" SoundDef
SoundDefOf --> "Mouseover_Tab" SoundDef
SoundDefOf --> "ThingSelected" SoundDef
SoundDefOf --> "MapSelected" SoundDef
SoundDefOf --> "ColonistSelected" SoundDef
SoundDefOf --> "ColonistOrdered" SoundDef
SoundDefOf --> "LetterArrive_BadUrgent" SoundDef
SoundDefOf --> "LetterArrive" SoundDef
SoundDefOf --> "Designate_DragStandard" SoundDef
SoundDefOf --> "Designate_DragStandard_Changed" SoundDef
SoundDefOf --> "Designate_DragBuilding" SoundDef
SoundDefOf --> "Designate_DragAreaAdd" SoundDef
SoundDefOf --> "Designate_DragAreaDelete" SoundDef
SoundDefOf --> "Designate_Failed" SoundDef
SoundDefOf --> "Designate_ZoneAdd" SoundDef
SoundDefOf --> "Designate_ZoneDelete" SoundDef
SoundDefOf --> "Designate_Cancel" SoundDef
SoundDefOf --> "Designate_Haul" SoundDef
SoundDefOf --> "Designate_Mine" SoundDef
SoundDefOf --> "Designate_SmoothSurface" SoundDef
SoundDefOf --> "Designate_PlanRemove" SoundDef
SoundDefOf --> "Designate_PlanAdd" SoundDef
SoundDefOf --> "Designate_Claim" SoundDef
SoundDefOf --> "Designate_Deconstruct" SoundDef
SoundDefOf --> "Designate_Hunt" SoundDef
SoundDefOf --> "Designate_PlaceBuilding" SoundDef
SoundDefOf --> "Designate_CutPlants" SoundDef
SoundDefOf --> "Designate_Harvest" SoundDef
SoundDefOf --> "Standard_Drop" SoundDef
SoundDefOf --> "Standard_Pickup" SoundDef
SoundDefOf --> "BulletImpact_Ground" SoundDef
SoundDefOf --> "Ambient_AltitudeWind" SoundDef
SoundDefOf --> "Ambient_Space" SoundDef
SoundDefOf --> "Power_OnSmall" SoundDef
SoundDefOf --> "Power_OffSmall" SoundDef
SoundDefOf --> "Thunder_OnMap" SoundDef
SoundDefOf --> "Thunder_OffMap" SoundDef
SoundDefOf --> "Interact_CleanFilth" SoundDef
SoundDefOf --> "Interact_Sow" SoundDef
SoundDefOf --> "Interact_Tend" SoundDef
SoundDefOf --> "Interact_BeatFire" SoundDef
SoundDefOf --> "Interact_Ignite" SoundDef
SoundDefOf --> "Roof_Start" SoundDef
SoundDefOf --> "Roof_Finish" SoundDef
SoundDefOf --> "Roof_Collapse" SoundDef
SoundDefOf --> "PsychicPulseGlobal" SoundDef
SoundDefOf --> "PsychicSootheGlobal" SoundDef
SoundDefOf --> "GeyserSpray" SoundDef
SoundDefOf --> "TurretAcquireTarget" SoundDef
SoundDefOf --> "FlickSwitch" SoundDef
SoundDefOf --> "PlayBilliards" SoundDef
SoundDefOf --> "Building_Complete" SoundDef
SoundDefOf --> "RawMeat_Eat" SoundDef
SoundDefOf --> "HissSmall" SoundDef
SoundDefOf --> "HissJet" SoundDef
SoundDefOf --> "MetalHitImportant" SoundDef
SoundDefOf --> "Door_OpenPowered" SoundDef
SoundDefOf --> "Door_ClosePowered" SoundDef
SoundDefOf --> "Door_OpenManual" SoundDef
SoundDefOf --> "Door_CloseManual" SoundDef
SoundDefOf --> "EnergyShield_AbsorbDamage" SoundDef
SoundDefOf --> "EnergyShield_Reset" SoundDef
SoundDefOf --> "EnergyShield_Broken" SoundDef
SoundDefOf --> "Pawn_Melee_Punch_HitPawn" SoundDef
SoundDefOf --> "Pawn_Melee_Punch_HitBuilding" SoundDef
SoundDefOf --> "Pawn_Melee_Punch_Miss" SoundDef
SoundDefOf --> "Artillery_ShellLoaded" SoundDef
SoundDefOf --> "TechMedicineUsed" SoundDef
SoundDefOf --> "OrbitalBeam" SoundDef
SoundDefOf --> "DropPod_Open" SoundDef
SoundDefOf --> "Building_Deconstructed" SoundDef
SoundDefOf --> "CryptosleepCasket_Accept" SoundDef
SoundDefOf --> "CryptosleepCasket_Eject" SoundDef
SoundDefOf --> "TrapSpring" SoundDef
SoundDefOf --> "TrapArm" SoundDef
SoundDefOf --> "FireBurning" SoundDef
SoundDefOf --> "Vomit" SoundDef
SoundDefOf --> "ResearchStart" SoundDef
SoundDefOf --> "ThingUninstalled" SoundDef
SoundDefOf --> "ShipTakeoff" SoundDef
SoundDefOf --> "Corpse_Drop" SoundDef
SoundDefOf --> "Tornado" SoundDef
SoundDefOf --> "Tunnel" SoundDef
SoundDefOf --> "Hive_Spawn" SoundDef
SoundDefOf --> "Interceptor_BlockProjectile" SoundDef
SoundDefOf --> "MechanoidsWakeUp" SoundDef
SoundDefOf --> "FlashstormAmbience" SoundDef
SoundDefOf --> "MechSerumUsed" SoundDef
SoundDefOf --> "WaterMill_Ambience" SoundDef
SoundDefOf --> "ShipReactor_Startup" SoundDef
SoundDefOf --> "Standard_Reload" SoundDef
SoundDefOf --> "WindTurbine_Ambience" SoundDef
SoundDefOf --> "Bombardment_PreImpact" SoundDef
SoundDefOf --> "PsycastPsychicEffect" SoundDef
SoundDefOf --> "PsycastPsychicPulse" SoundDef
SoundDefOf --> "Psycast_Skip_Pulse" SoundDef
SoundDefOf --> "Psycast_Skip_Exit" SoundDef
SoundDefOf --> "Psycast_Skip_Entry" SoundDef
SoundDefOf --> "PsycastCastLoop" SoundDef
SoundDefOf --> "PsychicEntropyOverloaded" SoundDef
SoundDefOf --> "PsychicEntropyHyperloaded" SoundDef
SoundDefOf --> "PsychicEntropyBrainCharring" SoundDef
SoundDefOf --> "PsychicEntropyBrainRoasting" SoundDef
SoundDefOf --> "MeditationGainPsyfocus" SoundDef
SoundDefOf --> "MechClusterDefeated" SoundDef
SoundDefOf --> "TechprintApplied" SoundDef
SoundDefOf --> "Bestowing_Start" SoundDef
SoundDefOf --> "Bestowing_Warmup" SoundDef
SoundDefOf --> "Bestowing_Finished" SoundDef
SoundDefOf --> "OrbitalStrike_Ordered" SoundDef
SoundDefOf --> "Broadshield_Startup" SoundDef
SoundDefOf --> "GameStartSting" SoundDef
SoundDefOf --> "PlanetkillerImpact" SoundDef
@enduml
