@startuml
class SpecialThingFilterWorker_NonSmeltableWeapons {
    + <<override>> Matches(t:Thing) : bool
    + <<override>> CanEverMatch(def:ThingDef) : bool
    + <<override>> AlwaysMatches(def:ThingDef) : bool
}
SpecialThingFilterWorker <|-- SpecialThingFilterWorker_NonSmeltableWeapons
@enduml
