@startuml
class SpecialThingFilterWorker_NonBiocodedWeapons {
    + <<override>> Matches(t:Thing) : bool
    + <<override>> CanEverMatch(def:ThingDef) : bool
}
SpecialThingFilterWorker <|-- SpecialThingFilterWorker_NonBiocodedWeapons
@enduml
