@startuml
class SpecialThingFilterWorker_NonBiocodedApparel {
    + <<override>> Matches(t:Thing) : bool
    + <<override>> CanEverMatch(def:ThingDef) : bool
}
SpecialThingFilterWorker <|-- SpecialThingFilterWorker_NonBiocodedApparel
@enduml
