@startuml
class SpecialThingFilterWorker_BiocodedApparel {
    + <<override>> Matches(t:Thing) : bool
    + <<override>> CanEverMatch(def:ThingDef) : bool
}
SpecialThingFilterWorker <|-- SpecialThingFilterWorker_BiocodedApparel
@enduml
