@startuml
class SpecialThingFilterWorker_DeadmansApparel {
    + <<override>> Matches(t:Thing) : bool
    + <<override>> CanEverMatch(def:ThingDef) : bool
}
SpecialThingFilterWorker <|-- SpecialThingFilterWorker_DeadmansApparel
@enduml
