@startuml
class StatPart_Resting {
    + factor : float = 1f
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_Resting
@enduml
