@startuml
class StatPart_Difficulty_ButcherYield {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_Difficulty_ButcherYield
@enduml
