@startuml
abstract class StatPart {
    + priority : float
    + {abstract} TransformValue(req:StatRequest, val:float) : void
    + {abstract} ExplanationPart(req:StatRequest) : string
    + <<virtual>> ConfigErrors() : IEnumerable<string>
    + <<virtual>> GetInfoCardHyperlinks(req:StatRequest) : IEnumerable<Dialog_InfoCard.Hyperlink>
}
StatPart --> "parentStat" StatDef
@enduml
