@startuml
class StatPart_Mood {
    + <<override>> ConfigErrors() : IEnumerable<string>
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_Mood
@enduml
