@startuml
class StatPart_AddedBodyPartsMass {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_AddedBodyPartsMass
@enduml
