@startuml
class StatPart_WeaponTraitsMarketValueOffset {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_WeaponTraitsMarketValueOffset
@enduml
