@startuml
class StatDefOf <<static>> {
    {static} StatDefOf()
}
StatDefOf --> "MaxHitPoints" StatDef
StatDefOf --> "MarketValue" StatDef
StatDefOf --> "MarketValueIgnoreHp" StatDef
StatDefOf --> "RoyalFavorValue" StatDef
StatDefOf --> "SellPriceFactor" StatDef
StatDefOf --> "Beauty" StatDef
StatDefOf --> "Cleanliness" StatDef
StatDefOf --> "Flammability" StatDef
StatDefOf --> "DeteriorationRate" StatDef
StatDefOf --> "WorkToMake" StatDef
StatDefOf --> "WorkToBuild" StatDef
StatDefOf --> "Mass" StatDef
StatDefOf --> "ConstructionSpeedFactor" StatDef
StatDefOf --> "Nutrition" StatDef
StatDefOf --> "FoodPoisonChanceFixedHuman" StatDef
StatDefOf --> "MoveSpeed" StatDef
StatDefOf --> "GlobalLearningFactor" StatDef
StatDefOf --> "HungerRateMultiplier" StatDef
StatDefOf --> "RestRateMultiplier" StatDef
StatDefOf --> "PsychicSensitivity" StatDef
StatDefOf --> "ToxicSensitivity" StatDef
StatDefOf --> "MentalBreakThreshold" StatDef
StatDefOf --> "EatingSpeed" StatDef
StatDefOf --> "ComfyTemperatureMin" StatDef
StatDefOf --> "ComfyTemperatureMax" StatDef
StatDefOf --> "Comfort" StatDef
StatDefOf --> "MeatAmount" StatDef
StatDefOf --> "LeatherAmount" StatDef
StatDefOf --> "MinimumHandlingSkill" StatDef
StatDefOf --> "MeleeDPS" StatDef
StatDefOf --> "PainShockThreshold" StatDef
StatDefOf --> "ForagedNutritionPerDay" StatDef
StatDefOf --> "PsychicEntropyMax" StatDef
StatDefOf --> "PsychicEntropyRecoveryRate" StatDef
StatDefOf --> "PsychicEntropyGain" StatDef
StatDefOf --> "MeditationFocusGain" StatDef
StatDefOf --> "WorkSpeedGlobal" StatDef
StatDefOf --> "MiningSpeed" StatDef
StatDefOf --> "DeepDrillingSpeed" StatDef
StatDefOf --> "MiningYield" StatDef
StatDefOf --> "ResearchSpeed" StatDef
StatDefOf --> "ConstructionSpeed" StatDef
StatDefOf --> "HuntingStealth" StatDef
StatDefOf --> "PlantWorkSpeed" StatDef
StatDefOf --> "SmoothingSpeed" StatDef
StatDefOf --> "FoodPoisonChance" StatDef
StatDefOf --> "CarryingCapacity" StatDef
StatDefOf --> "PlantHarvestYield" StatDef
StatDefOf --> "FixBrokenDownBuildingSuccessChance" StatDef
StatDefOf --> "ConstructSuccessChance" StatDef
StatDefOf --> "GeneralLaborSpeed" StatDef
StatDefOf --> "UnskilledLaborSpeed" StatDef
StatDefOf --> "MedicalTendSpeed" StatDef
StatDefOf --> "MedicalTendQuality" StatDef
StatDefOf --> "MedicalSurgerySuccessChance" StatDef
StatDefOf --> "NegotiationAbility" StatDef
StatDefOf --> "ArrestSuccessChance" StatDef
StatDefOf --> "TradePriceImprovement" StatDef
StatDefOf --> "SocialImpact" StatDef
StatDefOf --> "PawnBeauty" StatDef
StatDefOf --> "AnimalGatherSpeed" StatDef
StatDefOf --> "AnimalGatherYield" StatDef
StatDefOf --> "TameAnimalChance" StatDef
StatDefOf --> "TrainAnimalChance" StatDef
StatDefOf --> "ShootingAccuracyPawn" StatDef
StatDefOf --> "ShootingAccuracyTurret" StatDef
StatDefOf --> "AimingDelayFactor" StatDef
StatDefOf --> "MeleeHitChance" StatDef
StatDefOf --> "MeleeDodgeChance" StatDef
StatDefOf --> "PawnTrapSpringChance" StatDef
StatDefOf --> "IncomingDamageFactor" StatDef
StatDefOf --> "MeleeWeapon_AverageDPS" StatDef
StatDefOf --> "MeleeWeapon_DamageMultiplier" StatDef
StatDefOf --> "MeleeWeapon_CooldownMultiplier" StatDef
StatDefOf --> "MeleeWeapon_AverageArmorPenetration" StatDef
StatDefOf --> "SharpDamageMultiplier" StatDef
StatDefOf --> "BluntDamageMultiplier" StatDef
StatDefOf --> "StuffPower_Armor_Sharp" StatDef
StatDefOf --> "StuffPower_Armor_Blunt" StatDef
StatDefOf --> "StuffPower_Armor_Heat" StatDef
StatDefOf --> "StuffPower_Insulation_Cold" StatDef
StatDefOf --> "StuffPower_Insulation_Heat" StatDef
StatDefOf --> "RangedWeapon_Cooldown" StatDef
StatDefOf --> "RangedWeapon_DamageMultiplier" StatDef
StatDefOf --> "AccuracyTouch" StatDef
StatDefOf --> "AccuracyShort" StatDef
StatDefOf --> "AccuracyMedium" StatDef
StatDefOf --> "AccuracyLong" StatDef
StatDefOf --> "StuffEffectMultiplierArmor" StatDef
StatDefOf --> "StuffEffectMultiplierInsulation_Cold" StatDef
StatDefOf --> "StuffEffectMultiplierInsulation_Heat" StatDef
StatDefOf --> "ArmorRating_Sharp" StatDef
StatDefOf --> "ArmorRating_Blunt" StatDef
StatDefOf --> "ArmorRating_Heat" StatDef
StatDefOf --> "Insulation_Cold" StatDef
StatDefOf --> "Insulation_Heat" StatDef
StatDefOf --> "EnergyShieldRechargeRate" StatDef
StatDefOf --> "EnergyShieldEnergyMax" StatDef
StatDefOf --> "SmokepopBeltRadius" StatDef
StatDefOf --> "JumpRange" StatDef
StatDefOf --> "EquipDelay" StatDef
StatDefOf --> "MedicalPotency" StatDef
StatDefOf --> "MedicalQualityMax" StatDef
StatDefOf --> "ImmunityGainSpeed" StatDef
StatDefOf --> "ImmunityGainSpeedFactor" StatDef
StatDefOf --> "DoorOpenSpeed" StatDef
StatDefOf --> "BedRestEffectiveness" StatDef
StatDefOf --> "TrapMeleeDamage" StatDef
StatDefOf --> "TrapSpringChance" StatDef
StatDefOf --> "ResearchSpeedFactor" StatDef
StatDefOf --> "MedicalTendQualityOffset" StatDef
StatDefOf --> "WorkTableWorkSpeedFactor" StatDef
StatDefOf --> "WorkTableEfficiencyFactor" StatDef
StatDefOf --> "JoyGainFactor" StatDef
StatDefOf --> "SurgerySuccessChanceFactor" StatDef
StatDefOf --> "Ability_CastingTime" StatDef
StatDefOf --> "Ability_EntropyGain" StatDef
StatDefOf --> "Ability_PsyfocusCost" StatDef
StatDefOf --> "Ability_Duration" StatDef
StatDefOf --> "Ability_Range" StatDef
StatDefOf --> "Ability_EffectRadius" StatDef
StatDefOf --> "Ability_RequiredPsylink" StatDef
StatDefOf --> "Ability_GoodwillImpact" StatDef
StatDefOf --> "Ability_DetectChancePerEntropy" StatDef
StatDefOf --> "Bladelink_DetectionChance" StatDef
StatDefOf --> "MeditationFocusStrength" StatDef
@enduml
