@startuml
class StatPart_MaxChanceIfRotting {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_MaxChanceIfRotting
@enduml
