@startuml
class StatDisplayOrder <<static>> {
    + <<const>> Description : int = 99999
    + <<const>> Quality : int = 99999
    + <<const>> HitPointsBasic : int = 99998
    + <<const>> Race : int = 2100
    + <<const>> Race_Wildness : int = 2050
    + <<const>> Race_LeatherType : int = 3550
    + <<const>> Race_LifeExpectancy : int = 2000
    + <<const>> Race_Trainability : int = 2500
    + <<const>> Race_NutritationEatenPerDay : int = 1600
    + <<const>> Race_Diet : int = 1500
    + <<const>> Race_BodySize : int = 500
    + <<const>> Race_NuzzleInterval : int = 500
    + <<const>> Race_Animal_TameFailedRevengeChance : int = 511
    + <<const>> Race_Animal_HarmedRevengeChance : int = 510
    + <<const>> Race_Animal_PackAnimal : int = 2202
    + <<const>> Race_Animal_FilthRate : int = 2203
    + <<const>> Thing_CoverEffectiveness : int = 2000
    + <<const>> Thing_ConstructionSkillRequired : int = 1100
    + <<const>> Thing_Damage : int = 5500
    + <<const>> Thing_TerrainRequirement : int = 1101
    + <<const>> Thing_WorkToUninstall : int = 1102
    + <<const>> Thing_Stuff : int = 1100
    + <<const>> Thing_CreatedAt : int = 1103
    + <<const>> Thing_Meat_SourceSpecies : int = 1200
    + <<const>> Thing_Surgery_DeathOnFailChance : int = 4101
    + <<const>> Thing_Surgery_SuccessChanceFactor : int = 4102
    + <<const>> Thing_Apparel_Biocoded : int = 2753
    + <<const>> Thing_Apparel_Reloadable : int = 2749
    + <<const>> Thing_Apparel_Covers : int = 2750
    + <<const>> Thing_Apparel_Layer : int = 2751
    + <<const>> Thing_Apparel_MaxSatisfiedTitle : int = 2752
    + <<const>> Thing_Plant_Attributes : int = 4157
    + <<const>> Thing_Plant_FertilityRequirement : int = 4156
    + <<const>> Thing_Plant_FertilitySensitivity : int = 4155
    + <<const>> Thing_Plant_HarvestYield : int = 4150
    + <<const>> Thing_Plant_GrowingTime : int = 4158
    + <<const>> Thing_Plant_LifeSpan : int = 4150
    + <<const>> Thing_Plant_LightRequirement : int = 4154
    + <<const>> Thing_Plant_MinGrowingSkillToSow : int = 4151
    + <<const>> Thing_Plant_MaxGrowthTemperature : int = 4153
    + <<const>> Thing_Plant_MinGrowthTemperature : int = 4152
    + <<const>> Thing_Ingestible_MaxSatisfiedTitle : int = 4752
    + <<const>> Thing_Ingestible_Joy : int = 4751
    + <<const>> Thing_Drug_Chemical : int = 2490
    + <<const>> Thing_Drug_HighGainPerDose : int = 2480
    + <<const>> Thing_Drug_HighFallRate : int = 2470
    + <<const>> Thing_Drug_HighDurationPerDose : int = 2460
    + <<const>> Thing_Drug_ToleranceGainPerDose : int = 2450
    + <<const>> Thing_Drug_ToleranceFallRate : int = 2440
    + <<const>> Thing_Drug_NewAddictionMinTolerance : int = 2437
    + <<const>> Thing_Drug_SafeDoseInterval : int = 2435
    + <<const>> Thing_Drug_NewAddictionChance : int = 2428
    + <<const>> Thing_Drug_NewAddictionSeverity : int = 2427
    + <<const>> Thing_Drug_AddictionSeverityPerDose : int = 2424
    + <<const>> Thing_Drug_AddictionNeedOffset : int = 2420
    + <<const>> Thing_Drug_AddictionNeedFallRate : int = 2410
    + <<const>> Thing_Drug_AddictionNeedInterval : int = 2400
    + <<const>> Thing_Drug_AddictionRecoveryTime : int = 2395
    + <<const>> Thing_Drug_AddictionCostPerDay : int = 2390
    + <<const>> Thing_Drug_RandomODChance : int = 2380
    + <<const>> Thing_Drug_MedicineXpGainFactor : int = 1000
    + <<const>> Thing_Weapon_Biocoded : int = 5404
    + <<const>> Thing_Weapon_StoppingPower : int = 5402
    + <<const>> Thing_Weapon_ArmorPenetration : int = 5400
    + <<const>> Thing_Weapon_BurstShotFireRate : int = 5392
    + <<const>> Thing_Weapon_BurstShotCount : int = 5391
    + <<const>> Thing_Weapon_Range : int = 5390
    + <<const>> Thing_Weapon : int = 5389
    + <<const>> Thing_Weapon_MeleeWarmupTime : int = 3555
    + <<const>> Thing_Weapon_DirectHitChance : int = 3560
    + <<const>> Thing_Weapon_MissRadius : int = 3557
    + <<const>> Thing_Mineable : int = 2200
    + <<const>> Thing_Terrain_Supports : int = 2000
    + <<const>> Thing_PowerConsumption : int = 5000
    + <<const>> Thing_RearmCost : int = 3170
    + <<const>> Thing_ShotsBeforeRearm : int = 3171
    + <<const>> Thing_BodyPartEfficiency : int = 4000
    + <<const>> Thing_MoodChange : int = 3500
    + <<const>> Thing_TrapArmorPeneration : int = 3000
    + <<const>> Thing_JoyKind : int = 4750
    + <<const>> Thing_MinimumRoyalTitle : int = 2100
    + <<const>> Hediff_Affects : int = 4080
    + <<const>> Hediff_NaturalHealingFactor : int = 4020
    + <<const>> Hediff_FoodPoisoningChanceFactor : int = 4030
    + <<const>> Hediff_BleedingRate : int = 4040
    + <<const>> Hediff_TotalBleedingFactor : int = 4041
    + <<const>> Hediff_HungerRateFactor : int = 4051
    + <<const>> Hediff_TirednessFactor : int = 4050
    + <<const>> Hediff_HungerRateOffset : int = 4051
    + <<const>> Hediff_TirednessOffset : int = 4050
    + <<const>> Hediff_Pain : int = 4050
    + <<const>> Hediff_PartEfficiency : int = 4050
    + <<const>> Hediff_PreventsInfection : int = 4050
    + <<const>> Hediff_StatModification : int = 4070
    + <<const>> Hediff_CapacityModification : int = 4060
    + <<const>> Recipe_EfficiencyStat : int = 4401
    + <<const>> Recipe_Ingredients : int = 4405
    + <<const>> Recipe_Products : int = 4405
    + <<const>> Recipe_Skill : int = 4404
    + <<const>> Recipe_SkillRequirements : int = 4403
    + <<const>> Recipe_WorkSpeedStat : int = 4402
    + <<const>> Title_Permits : int = 99999
    + <<const>> Title_ApparelRequirements : int = 99998
    + <<const>> Title_RoomRequirements : int = 99997
    + <<const>> Title_RequiredMeals : int = 99995
    + <<const>> Title_DisabledWorkTypes : int = 99994
    + <<const>> Meditation_FocusesAvailable : int = 99995
}
@enduml
