@startuml
class StatPart_WornByCorpse {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_WornByCorpse
@enduml
