@startuml
class StatPart_Difficulty {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_Difficulty
@enduml
