@startuml
class StatPart_ReloadMarketValue {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_ReloadMarketValue
@enduml
