@startuml
class StatPart_UnfinishedThingIngredientsMass {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_UnfinishedThingIngredientsMass
@enduml
