@startuml
class StatPart_GearAndInventoryMass {
    + <<override>> TransformValue(req:StatRequest, val:float) : void
    + <<override>> ExplanationPart(req:StatRequest) : string
}
StatPart <|-- StatPart_GearAndInventoryMass
@enduml
