@startuml
class StockGenerator_BuySlaves {
    + <<override>> GenerateThings(forTile:int, faction:Faction) : IEnumerable<Thing>
    + <<override>> HandlesThingDef(thingDef:ThingDef) : bool
}
StockGenerator <|-- StockGenerator_BuySlaves
@enduml
