@startuml
class StorytellerComp_SingleMTB {
    + <<override>> MakeIntervalIncidents(target:IIncidentTarget) : IEnumerable<FiringIncident>
    + <<override>> ToString() : string
}
StorytellerComp <|-- StorytellerComp_SingleMTB
@enduml
