@startuml
class StorytellerComp_DeepDrillInfestation {
    + <<override>> MakeIntervalIncidents(target:IIncidentTarget) : IEnumerable<FiringIncident>
}
StorytellerComp <|-- StorytellerComp_DeepDrillInfestation
@enduml
