@startuml
class StorytellerCompProperties_RefiringUniqueQuest {
    + refireEveryDays : float
    + StorytellerCompProperties_RefiringUniqueQuest()
}
StorytellerCompProperties <|-- StorytellerCompProperties_RefiringUniqueQuest
StorytellerCompProperties_RefiringUniqueQuest --> "incident" IncidentDef
@enduml
