@startuml
class StorytellerComp_ClassicIntro {
    + <<override>> MakeIntervalIncidents(target:IIncidentTarget) : IEnumerable<FiringIncident>
}
StorytellerComp <|-- StorytellerComp_ClassicIntro
@enduml
