@startuml
class StorytellerCompProperties_DeepDrillInfestation {
    + baseMtbDaysPerDrill : float
    + StorytellerCompProperties_DeepDrillInfestation()
}
StorytellerCompProperties <|-- StorytellerCompProperties_DeepDrillInfestation
@enduml
