@startuml
class StorytellerComp_CategoryIndividualMTBByBiome {
    + <<override>> MakeIntervalIncidents(target:IIncidentTarget) : IEnumerable<FiringIncident>
    + <<override>> ToString() : string
}
StorytellerComp <|-- StorytellerComp_CategoryIndividualMTBByBiome
@enduml
