@startuml
class StorytellerCompProperties_SingleMTB {
    + mtbDays : float = 13f
    + StorytellerCompProperties_SingleMTB()
}
StorytellerCompProperties <|-- StorytellerCompProperties_SingleMTB
StorytellerCompProperties_SingleMTB --> "incident" IncidentDef
@enduml
