@startuml
class StorytellerComp_OnOffCycle {
    + <<override>> MakeIntervalIncidents(target:IIncidentTarget) : IEnumerable<FiringIncident>
    + <<override>> ToString() : string
}
StorytellerComp <|-- StorytellerComp_OnOffCycle
@enduml
