@startuml
class StorytellerComp_ThreatsGenerator {
    + <<override>> MakeIntervalIncidents(target:IIncidentTarget) : IEnumerable<FiringIncident>
}
StorytellerComp <|-- StorytellerComp_ThreatsGenerator
@enduml
