@startuml
class StuffCategoryDef {
}
Def <|-- StuffCategoryDef
StuffCategoryDef --> "destroySoundSmall" SoundDef
StuffCategoryDef --> "destroySoundMedium" SoundDef
StuffCategoryDef --> "destroySoundLarge" SoundDef
@enduml
