@startuml
class TaleDefOf <<static>> {
    {static} TaleDefOf()
}
TaleDefOf --> "FinishedResearchProject" TaleDef
TaleDefOf --> "ExecutedPrisoner" TaleDef
TaleDefOf --> "KidnappedColonist" TaleDef
TaleDefOf --> "SoldPrisoner" TaleDef
TaleDefOf --> "TamedAnimal" TaleDef
TaleDefOf --> "TrainedAnimal" TaleDef
TaleDefOf --> "AteRawHumanlikeMeat" TaleDef
TaleDefOf --> "WalkedNaked" TaleDef
TaleDefOf --> "ButcheredHumanlikeCorpse" TaleDef
TaleDefOf --> "WasOnFire" TaleDef
TaleDefOf --> "Hunted" TaleDef
TaleDefOf --> "Captured" TaleDef
TaleDefOf --> "Vomited" TaleDef
TaleDefOf --> "StruckMineable" TaleDef
TaleDefOf --> "DidSurgery" TaleDef
TaleDefOf --> "Recruited" TaleDef
TaleDefOf --> "LandedInPod" TaleDef
TaleDefOf --> "CraftedArt" TaleDef
TaleDefOf --> "TradedWith" TaleDef
TaleDefOf --> "BuriedCorpse" TaleDef
TaleDefOf --> "IllnessRevealed" TaleDef
TaleDefOf --> "KilledBy" TaleDef
TaleDefOf --> "KilledColonist" TaleDef
TaleDefOf --> "KilledColonyAnimal" TaleDef
TaleDefOf --> "BondedWithAnimal" TaleDef
TaleDefOf --> "BecameLover" TaleDef
TaleDefOf --> "Marriage" TaleDef
TaleDefOf --> "Breakup" TaleDef
TaleDefOf --> "CaravanAmbushedByHumanlike" TaleDef
TaleDefOf --> "CaravanFormed" TaleDef
TaleDefOf --> "CaravanFled" TaleDef
TaleDefOf --> "CaravanAmbushDefeated" TaleDef
TaleDefOf --> "CaravanRemoteMining" TaleDef
TaleDefOf --> "CaravanAssaultSuccessful" TaleDef
TaleDefOf --> "MinedValuable" TaleDef
TaleDefOf --> "CompletedLongConstructionProject" TaleDef
TaleDefOf --> "CompletedLongCraftingProject" TaleDef
TaleDefOf --> "AttendedParty" TaleDef
TaleDefOf --> "AttendedConcert" TaleDef
TaleDefOf --> "HeldConcert" TaleDef
TaleDefOf --> "GainedMasterSkillWithPassion" TaleDef
TaleDefOf --> "GainedMasterSkillWithoutPassion" TaleDef
TaleDefOf --> "IncreasedMenagerie" TaleDef
TaleDefOf --> "Wounded" TaleDef
TaleDefOf --> "Downed" TaleDef
TaleDefOf --> "KilledLongRange" TaleDef
TaleDefOf --> "KilledMelee" TaleDef
TaleDefOf --> "KilledMajorThreat" TaleDef
TaleDefOf --> "KilledCapacity" TaleDef
TaleDefOf --> "KilledMortar" TaleDef
TaleDefOf --> "DefeatedHostileFactionLeader" TaleDef
TaleDefOf --> "Exhausted" TaleDef
TaleDefOf --> "GaveBirth" TaleDef
TaleDefOf --> "LaunchedShip" TaleDef
TaleDefOf --> "SocialFight" TaleDef
TaleDefOf --> "CollapseDodged" TaleDef
@enduml
