@startuml
abstract class TaleData {
    + {abstract} ExposeData() : void
    + <<virtual>> GetRules(prefix:string) : IEnumerable<Rule>
    + <<virtual>> GetRules() : IEnumerable<Rule>
}
IExposable <|-- TaleData
@enduml
