@startuml
class ThingSetMakerDef {
    + <<override>> ResolveReferences() : void
}
Def <|-- ThingSetMakerDef
ThingSetMakerDef --> "root" ThingSetMaker
ThingSetMakerDef --> "debugParams" ThingSetMakerParams
@enduml
