@startuml
class ThingDefOf <<static>> {
    {static} ThingDefOf()
}
ThingDefOf --> "Silver" ThingDef
ThingDefOf --> "Gold" ThingDef
ThingDefOf --> "Steel" ThingDef
ThingDefOf --> "WoodLog" ThingDef
ThingDefOf --> "MedicineHerbal" ThingDef
ThingDefOf --> "MedicineIndustrial" ThingDef
ThingDefOf --> "MedicineUltratech" ThingDef
ThingDefOf --> "BlocksGranite" ThingDef
ThingDefOf --> "Plasteel" ThingDef
ThingDefOf --> "Beer" ThingDef
ThingDefOf --> "SmokeleafJoint" ThingDef
ThingDefOf --> "Chocolate" ThingDef
ThingDefOf --> "ComponentIndustrial" ThingDef
ThingDefOf --> "ComponentSpacer" ThingDef
ThingDefOf --> "InsectJelly" ThingDef
ThingDefOf --> "Cloth" ThingDef
ThingDefOf --> "Leather_Plain" ThingDef
ThingDefOf --> "Hyperweave" ThingDef
ThingDefOf --> "RawPotatoes" ThingDef
ThingDefOf --> "RawBerries" ThingDef
ThingDefOf --> "Granite" ThingDef
ThingDefOf --> "Wort" ThingDef
ThingDefOf --> "AIPersonaCore" ThingDef
ThingDefOf --> "TechprofSubpersonaCore" ThingDef
ThingDefOf --> "OrbitalTargeterBombardment" ThingDef
ThingDefOf --> "OrbitalTargeterPowerBeam" ThingDef
ThingDefOf --> "Chemfuel" ThingDef
ThingDefOf --> "Uranium" ThingDef
ThingDefOf --> "Jade" ThingDef
ThingDefOf --> "Shell_HighExplosive" ThingDef
ThingDefOf --> "Shell_AntigrainWarhead" ThingDef
ThingDefOf --> "MealSurvivalPack" ThingDef
ThingDefOf --> "MealNutrientPaste" ThingDef
ThingDefOf --> "MealSimple" ThingDef
ThingDefOf --> "MealFine" ThingDef
ThingDefOf --> "Pemmican" ThingDef
ThingDefOf --> "Kibble" ThingDef
ThingDefOf --> "Hay" ThingDef
ThingDefOf --> "Meat_Human" ThingDef
ThingDefOf --> "Luciferium" ThingDef
ThingDefOf --> "DropPodIncoming" ThingDef
ThingDefOf --> "DropPodLeaving" ThingDef
ThingDefOf --> "ShipChunkIncoming" ThingDef
ThingDefOf --> "CrashedShipPartIncoming" ThingDef
ThingDefOf --> "MeteoriteIncoming" ThingDef
ThingDefOf --> "ShuttleIncoming" ThingDef
ThingDefOf --> "ShuttleLeaving" ThingDef
ThingDefOf --> "ShuttleCrashing" ThingDef
ThingDefOf --> "PawnJumper" ThingDef
ThingDefOf --> "ActiveDropPod" ThingDef
ThingDefOf --> "Fire" ThingDef
ThingDefOf --> "Heart" ThingDef
ThingDefOf --> "ChunkSlagSteel" ThingDef
ThingDefOf --> "SteamGeyser" ThingDef
ThingDefOf --> "Hive" ThingDef
ThingDefOf --> "ShipChunk" ThingDef
ThingDefOf --> "ElephantTusk" ThingDef
ThingDefOf --> "GlowPod" ThingDef
ThingDefOf --> "MinifiedThing" ThingDef
ThingDefOf --> "MonumentMarker" ThingDef
ThingDefOf --> "PsychicAmplifier" ThingDef
ThingDefOf --> "Filth_Blood" ThingDef
ThingDefOf --> "Filth_AmnioticFluid" ThingDef
ThingDefOf --> "Filth_Dirt" ThingDef
ThingDefOf --> "Filth_Vomit" ThingDef
ThingDefOf --> "Filth_AnimalFilth" ThingDef
ThingDefOf --> "Filth_Trash" ThingDef
ThingDefOf --> "Filth_Slime" ThingDef
ThingDefOf --> "Filth_FireFoam" ThingDef
ThingDefOf --> "Filth_Fuel" ThingDef
ThingDefOf --> "Filth_RubbleRock" ThingDef
ThingDefOf --> "Filth_RubbleBuilding" ThingDef
ThingDefOf --> "Filth_CorpseBile" ThingDef
ThingDefOf --> "Filth_Ash" ThingDef
ThingDefOf --> "Filth_MachineBits" ThingDef
ThingDefOf --> "Filth_Water" ThingDef
ThingDefOf --> "RectTrigger" ThingDef
ThingDefOf --> "TriggerUnfogged" ThingDef
ThingDefOf --> "Explosion" ThingDef
ThingDefOf --> "Bombardment" ThingDef
ThingDefOf --> "PowerBeam" ThingDef
ThingDefOf --> "SignalAction_Letter" ThingDef
ThingDefOf --> "SignalAction_Ambush" ThingDef
ThingDefOf --> "Blight" ThingDef
ThingDefOf --> "Tornado" ThingDef
ThingDefOf --> "TunnelHiveSpawner" ThingDef
ThingDefOf --> "Flashstorm" ThingDef
ThingDefOf --> "Sandstone" ThingDef
ThingDefOf --> "Ship_Beam" ThingDef
ThingDefOf --> "Ship_Reactor" ThingDef
ThingDefOf --> "Ship_CryptosleepCasket" ThingDef
ThingDefOf --> "Ship_ComputerCore" ThingDef
ThingDefOf --> "Ship_Engine" ThingDef
ThingDefOf --> "Ship_SensorCluster" ThingDef
ThingDefOf --> "MineableSteel" ThingDef
ThingDefOf --> "MineableComponentsIndustrial" ThingDef
ThingDefOf --> "MineableGold" ThingDef
ThingDefOf --> "RaisedRocks" ThingDef
ThingDefOf --> "Door" ThingDef
ThingDefOf --> "Wall" ThingDef
ThingDefOf --> "Bed" ThingDef
ThingDefOf --> "Bedroll" ThingDef
ThingDefOf --> "SleepingSpot" ThingDef
ThingDefOf --> "OrbitalTradeBeacon" ThingDef
ThingDefOf --> "NutrientPasteDispenser" ThingDef
ThingDefOf --> "Grave" ThingDef
ThingDefOf --> "Sandbags" ThingDef
ThingDefOf --> "Barricade" ThingDef
ThingDefOf --> "AncientCryptosleepCasket" ThingDef
ThingDefOf --> "CryptosleepCasket" ThingDef
ThingDefOf --> "SolarGenerator" ThingDef
ThingDefOf --> "WoodFiredGenerator" ThingDef
ThingDefOf --> "PowerConduit" ThingDef
ThingDefOf --> "Battery" ThingDef
ThingDefOf --> "GeothermalGenerator" ThingDef
ThingDefOf --> "WatermillGenerator" ThingDef
ThingDefOf --> "Hopper" ThingDef
ThingDefOf --> "BilliardsTable" ThingDef
ThingDefOf --> "Telescope" ThingDef
ThingDefOf --> "MarriageSpot" ThingDef
ThingDefOf --> "PartySpot" ThingDef
ThingDefOf --> "MeditationSpot" ThingDef
ThingDefOf --> "RoyalBed" ThingDef
ThingDefOf --> "TrapSpike" ThingDef
ThingDefOf --> "Cooler" ThingDef
ThingDefOf --> "Heater" ThingDef
ThingDefOf --> "Snowman" ThingDef
ThingDefOf --> "WindTurbine" ThingDef
ThingDefOf --> "FermentingBarrel" ThingDef
ThingDefOf --> "DeepDrill" ThingDef
ThingDefOf --> "LongRangeMineralScanner" ThingDef
ThingDefOf --> "GroundPenetratingScanner" ThingDef
ThingDefOf --> "CollapsedRocks" ThingDef
ThingDefOf --> "TorchLamp" ThingDef
ThingDefOf --> "StandingLamp" ThingDef
ThingDefOf --> "Campfire" ThingDef
ThingDefOf --> "FirefoamPopper" ThingDef
ThingDefOf --> "PassiveCooler" ThingDef
ThingDefOf --> "CaravanPackingSpot" ThingDef
ThingDefOf --> "PlantPot" ThingDef
ThingDefOf --> "Table1x2c" ThingDef
ThingDefOf --> "Table2x2c" ThingDef
ThingDefOf --> "Table3x3c" ThingDef
ThingDefOf --> "DiningChair" ThingDef
ThingDefOf --> "Stool" ThingDef
ThingDefOf --> "PsychicEmanator" ThingDef
ThingDefOf --> "VanometricPowerCell" ThingDef
ThingDefOf --> "InfiniteChemreactor" ThingDef
ThingDefOf --> "CommsConsole" ThingDef
ThingDefOf --> "Sarcophagus" ThingDef
ThingDefOf --> "Turret_Mortar" ThingDef
ThingDefOf --> "Turret_MiniTurret" ThingDef
ThingDefOf --> "Turret_AutoMiniTurret" ThingDef
ThingDefOf --> "MechCapsule" ThingDef
ThingDefOf --> "DefoliatorShipPart" ThingDef
ThingDefOf --> "PsychicDronerShipPart" ThingDef
ThingDefOf --> "Column" ThingDef
ThingDefOf --> "Urn" ThingDef
ThingDefOf --> "SteleLarge" ThingDef
ThingDefOf --> "SteleGrand" ThingDef
ThingDefOf --> "PsychicDroner" ThingDef
ThingDefOf --> "Shuttle" ThingDef
ThingDefOf --> "Drape" ThingDef
ThingDefOf --> "ActivatorProximity" ThingDef
ThingDefOf --> "ShieldGeneratorBullets" ThingDef
ThingDefOf --> "ShieldGeneratorMortar" ThingDef
ThingDefOf --> "BroadshieldProjector" ThingDef
ThingDefOf --> "Brazier" ThingDef
ThingDefOf --> "ShuttleCrashed" ThingDef
ThingDefOf --> "Plant_Potato" ThingDef
ThingDefOf --> "Plant_TreeOak" ThingDef
ThingDefOf --> "Plant_Grass" ThingDef
ThingDefOf --> "Plant_Ambrosia" ThingDef
ThingDefOf --> "Plant_Dandelion" ThingDef
ThingDefOf --> "BurnedTree" ThingDef
ThingDefOf --> "Plant_TreeAnima" ThingDef
ThingDefOf --> "AnimusStone" ThingDef
ThingDefOf --> "NatureShrine_Small" ThingDef
ThingDefOf --> "NatureShrine_Large" ThingDef
ThingDefOf --> "Human" ThingDef
ThingDefOf --> "Muffalo" ThingDef
ThingDefOf --> "Dromedary" ThingDef
ThingDefOf --> "Cow" ThingDef
ThingDefOf --> "Thrumbo" ThingDef
ThingDefOf --> "Spark" ThingDef
ThingDefOf --> "Apparel_ShieldBelt" ThingDef
ThingDefOf --> "Apparel_SmokepopBelt" ThingDef
ThingDefOf --> "Apparel_Parka" ThingDef
ThingDefOf --> "Apparel_Tuque" ThingDef
ThingDefOf --> "Apparel_RobeRoyal" ThingDef
ThingDefOf --> "Mote_Text" ThingDef
ThingDefOf --> "Mote_ShotFlash" ThingDef
ThingDefOf --> "Mote_DustPuff" ThingDef
ThingDefOf --> "Mote_DustPuffThick" ThingDef
ThingDefOf --> "Mote_TornadoDustPuff" ThingDef
ThingDefOf --> "Mote_TempRoof" ThingDef
ThingDefOf --> "Mote_HealingCross" ThingDef
ThingDefOf --> "Mote_SleepZ" ThingDef
ThingDefOf --> "Mote_Heart" ThingDef
ThingDefOf --> "Mote_Meditating" ThingDef
ThingDefOf --> "Mote_IncapIcon" ThingDef
ThingDefOf --> "Mote_FeedbackGoto" ThingDef
ThingDefOf --> "Mote_FeedbackShoot" ThingDef
ThingDefOf --> "Mote_FeedbackMelee" ThingDef
ThingDefOf --> "Mote_FeedbackEquip" ThingDef
ThingDefOf --> "Mote_ExplosionFlash" ThingDef
ThingDefOf --> "Mote_FireGlow" ThingDef
ThingDefOf --> "Mote_MicroSparks" ThingDef
ThingDefOf --> "Mote_HeatGlow" ThingDef
ThingDefOf --> "Mote_Footprint" ThingDef
ThingDefOf --> "Mote_ShotHit_Spark" ThingDef
ThingDefOf --> "Mote_ShotHit_Dirt" ThingDef
ThingDefOf --> "Mote_Smoke" ThingDef
ThingDefOf --> "Mote_AirPuff" ThingDef
ThingDefOf --> "Mote_Horseshoe" ThingDef
ThingDefOf --> "Mote_Stone" ThingDef
ThingDefOf --> "Mote_ColonistFleeing" ThingDef
ThingDefOf --> "Mote_ColonistAttacking" ThingDef
ThingDefOf --> "Mote_Danger" ThingDef
ThingDefOf --> "Mote_Speech" ThingDef
ThingDefOf --> "Mote_ThoughtBad" ThingDef
ThingDefOf --> "Mote_ThoughtGood" ThingDef
ThingDefOf --> "Mote_MetaPuff" ThingDef
ThingDefOf --> "Mote_LightningGlow" ThingDef
ThingDefOf --> "Mote_Stun" ThingDef
ThingDefOf --> "Mote_WaterSplash" ThingDef
ThingDefOf --> "Mote_Bombardment" ThingDef
ThingDefOf --> "Mote_PowerBeam" ThingDef
ThingDefOf --> "Mote_Leaf" ThingDef
ThingDefOf --> "Mote_ForceJob" ThingDef
ThingDefOf --> "Mote_ForceJobMaintained" ThingDef
ThingDefOf --> "Mote_PsycastPsychicLine" ThingDef
ThingDefOf --> "Mote_PsycastPsychicEffect" ThingDef
ThingDefOf --> "Mote_PsycastAreaEffect" ThingDef
ThingDefOf --> "Mote_LineEMP" ThingDef
ThingDefOf --> "Mote_WaterskipSplashParticles" ThingDef
ThingDefOf --> "Mote_CastPsycast" ThingDef
ThingDefOf --> "Mote_EntropyPulse" ThingDef
ThingDefOf --> "Mote_PsychicLinkLine" ThingDef
ThingDefOf --> "Mote_PsychicLinkPulse" ThingDef
ThingDefOf --> "Mote_PsyfocusPulse" ThingDef
ThingDefOf --> "Mote_PsycastSkipFlashEntry" ThingDef
ThingDefOf --> "Mote_PsycastSkipInnerExit" ThingDef
ThingDefOf --> "Mote_PsycastSkipOuterRingEntry" ThingDef
ThingDefOf --> "Mote_PsycastSkipOuterRingExit" ThingDef
ThingDefOf --> "Mote_Bestow" ThingDef
ThingDefOf --> "Mote_BroadshieldActivation" ThingDef
ThingDefOf --> "Gas_Smoke" ThingDef
ThingDefOf --> "Throne" ThingDef
ThingDefOf --> "Harp" ThingDef
ThingDefOf --> "Harpsichord" ThingDef
ThingDefOf --> "Piano" ThingDef
ThingDefOf --> "MeleeWeapon_PsyfocusStaff" ThingDef
ThingDefOf --> "ShipLandingBeacon" ThingDef
ThingDefOf --> "ActivatorCountdown" ThingDef
@enduml
