@startuml
class Thought_WeaponTrait {
    + <<override>> ShouldDiscard : bool <<get>>
    + <<override>> LabelCap : string <<get>>
    + <<override>> Description : string <<get>>
    + <<override>> ExposeData() : void
}
Thought_Memory <|-- Thought_WeaponTrait
Thought_WeaponTrait --> "weapon" ThingWithComps
@enduml
