@startuml
class ThoughtDefOf <<static>> {
    {static} ThoughtDefOf()
}
ThoughtDefOf --> "AteRawFood" ThoughtDef
ThoughtDefOf --> "AteAwfulMeal" ThoughtDef
ThoughtDefOf --> "AteFineMeal" ThoughtDef
ThoughtDefOf --> "AteLavishMeal" ThoughtDef
ThoughtDefOf --> "AteHumanlikeMeatDirect" ThoughtDef
ThoughtDefOf --> "AteHumanlikeMeatDirectCannibal" ThoughtDef
ThoughtDefOf --> "AteHumanlikeMeatAsIngredient" ThoughtDef
ThoughtDefOf --> "AteHumanlikeMeatAsIngredientCannibal" ThoughtDef
ThoughtDefOf --> "AteInsectMeatDirect" ThoughtDef
ThoughtDefOf --> "AteInsectMeatAsIngredient" ThoughtDef
ThoughtDefOf --> "AteCorpse" ThoughtDef
ThoughtDefOf --> "AteRottenFood" ThoughtDef
ThoughtDefOf --> "AteFoodInappropriateForTitle" ThoughtDef
ThoughtDefOf --> "SleptInBedroom" ThoughtDef
ThoughtDefOf --> "SleptInBarracks" ThoughtDef
ThoughtDefOf --> "SleptOutside" ThoughtDef
ThoughtDefOf --> "SleptOnGround" ThoughtDef
ThoughtDefOf --> "SleptInCold" ThoughtDef
ThoughtDefOf --> "SleptInHeat" ThoughtDef
ThoughtDefOf --> "SleepDisturbed" ThoughtDef
ThoughtDefOf --> "ReignedInThroneroom" ThoughtDef
ThoughtDefOf --> "WasImprisoned" ThoughtDef
ThoughtDefOf --> "NewColonyOptimism" ThoughtDef
ThoughtDefOf --> "AteWithoutTable" ThoughtDef
ThoughtDefOf --> "AteInImpressiveDiningRoom" ThoughtDef
ThoughtDefOf --> "JoyActivityInImpressiveRecRoom" ThoughtDef
ThoughtDefOf --> "Catharsis" ThoughtDef
ThoughtDefOf --> "MyOrganHarvested" ThoughtDef
ThoughtDefOf --> "KnowColonistDied" ThoughtDef
ThoughtDefOf --> "KnowPrisonerDiedInnocent" ThoughtDef
ThoughtDefOf --> "KnowGuestOrganHarvested" ThoughtDef
ThoughtDefOf --> "KnowColonistOrganHarvested" ThoughtDef
ThoughtDefOf --> "KnowGuestExecuted" ThoughtDef
ThoughtDefOf --> "KnowColonistExecuted" ThoughtDef
ThoughtDefOf --> "KnowPrisonerSold" ThoughtDef
ThoughtDefOf --> "FreedFromSlavery" ThoughtDef
ThoughtDefOf --> "ReleasedHealthyPrisoner" ThoughtDef
ThoughtDefOf --> "SoldMyBondedAnimalMood" ThoughtDef
ThoughtDefOf --> "WitnessedDeathNonAlly" ThoughtDef
ThoughtDefOf --> "WitnessedDeathAlly" ThoughtDef
ThoughtDefOf --> "WitnessedDeathBloodlust" ThoughtDef
ThoughtDefOf --> "WitnessedDeathFamily" ThoughtDef
ThoughtDefOf --> "KilledHumanlikeBloodlust" ThoughtDef
ThoughtDefOf --> "ButcheredHumanlikeCorpse" ThoughtDef
ThoughtDefOf --> "KnowButcheredHumanlikeCorpse" ThoughtDef
ThoughtDefOf --> "ObservedLayingRottingCorpse" ThoughtDef
ThoughtDefOf --> "ObservedLayingCorpse" ThoughtDef
ThoughtDefOf --> "RapportBuilt" ThoughtDef
ThoughtDefOf --> "Nuzzled" ThoughtDef
ThoughtDefOf --> "ArtifactMoodBoost" ThoughtDef
ThoughtDefOf --> "KnowBuriedInSarcophagus" ThoughtDef
ThoughtDefOf --> "DebugGood" ThoughtDef
ThoughtDefOf --> "DebugBad" ThoughtDef
ThoughtDefOf --> "ColonistBanished" ThoughtDef
ThoughtDefOf --> "ColonistBanishedToDie" ThoughtDef
ThoughtDefOf --> "PrisonerBanishedToDie" ThoughtDef
ThoughtDefOf --> "BondedAnimalBanished" ThoughtDef
ThoughtDefOf --> "FailedToRescueRelative" ThoughtDef
ThoughtDefOf --> "RescuedRelative" ThoughtDef
ThoughtDefOf --> "Rescued" ThoughtDef
ThoughtDefOf --> "DecreeMet" ThoughtDef
ThoughtDefOf --> "KillThirst" ThoughtDef
ThoughtDefOf --> "JealousRage" ThoughtDef
ThoughtDefOf --> "ColonistLost" ThoughtDef
ThoughtDefOf --> "PawnWithGoodOpinionLost" ThoughtDef
ThoughtDefOf --> "PawnWithBadOpinionLost" ThoughtDef
ThoughtDefOf --> "ApparelDamaged" ThoughtDef
ThoughtDefOf --> "Naked" ThoughtDef
ThoughtDefOf --> "ClothedNudist" ThoughtDef
ThoughtDefOf --> "DeadMansApparel" ThoughtDef
ThoughtDefOf --> "HumanLeatherApparelSad" ThoughtDef
ThoughtDefOf --> "HumanLeatherApparelHappy" ThoughtDef
ThoughtDefOf --> "DecreeUnmet" ThoughtDef
ThoughtDefOf --> "Chitchat" ThoughtDef
ThoughtDefOf --> "PawnWithGoodOpinionDied" ThoughtDef
ThoughtDefOf --> "PawnWithBadOpinionDied" ThoughtDef
ThoughtDefOf --> "HadAngeringFight" ThoughtDef
ThoughtDefOf --> "HadCatharticFight" ThoughtDef
ThoughtDefOf --> "HarmedMe" ThoughtDef
ThoughtDefOf --> "BotchedMySurgery" ThoughtDef
ThoughtDefOf --> "CheatedOnMe" ThoughtDef
ThoughtDefOf --> "RebuffedMyRomanceAttempt" ThoughtDef
ThoughtDefOf --> "FailedRomanceAttemptOnMe" ThoughtDef
ThoughtDefOf --> "FailedRomanceAttemptOnMeLowOpinionMood" ThoughtDef
ThoughtDefOf --> "BrokeUpWithMe" ThoughtDef
ThoughtDefOf --> "DivorcedMe" ThoughtDef
ThoughtDefOf --> "RejectedMyProposal" ThoughtDef
ThoughtDefOf --> "RejectedMyProposalMood" ThoughtDef
ThoughtDefOf --> "IRejectedTheirProposal" ThoughtDef
ThoughtDefOf --> "GotMarried" ThoughtDef
ThoughtDefOf --> "HoneymoonPhase" ThoughtDef
ThoughtDefOf --> "RescuedMe" ThoughtDef
ThoughtDefOf --> "RescuedMeByOfferingHelp" ThoughtDef
ThoughtDefOf --> "RecruitedMe" ThoughtDef
ThoughtDefOf --> "AttendedWedding" ThoughtDef
ThoughtDefOf --> "AttendedParty" ThoughtDef
ThoughtDefOf --> "AttendedConcert" ThoughtDef
ThoughtDefOf --> "HeldConcert" ThoughtDef
ThoughtDefOf --> "TerribleSpeech" ThoughtDef
ThoughtDefOf --> "UninspiringSpeech" ThoughtDef
ThoughtDefOf --> "EncouragingSpeech" ThoughtDef
ThoughtDefOf --> "InspirationalSpeech" ThoughtDef
ThoughtDefOf --> "CrashedTogether" ThoughtDef
ThoughtDefOf --> "Insulted" ThoughtDef
ThoughtDefOf --> "KindWords" ThoughtDef
ThoughtDefOf --> "GotSomeLovin" ThoughtDef
ThoughtDefOf --> "KilledMyFriend" ThoughtDef
ThoughtDefOf --> "KilledMyRival" ThoughtDef
ThoughtDefOf --> "DefeatedHostileFactionLeader" ThoughtDef
ThoughtDefOf --> "DefeatedMechCluster" ThoughtDef
ThoughtDefOf --> "ForcedMeToTakeDrugs" ThoughtDef
ThoughtDefOf --> "ForcedMeToTakeLuciferium" ThoughtDef
ThoughtDefOf --> "OtherTravelerDied" ThoughtDef
ThoughtDefOf --> "OtherTravelerArrested" ThoughtDef
ThoughtDefOf --> "OtherTravelerSurgicallyViolated" ThoughtDef
ThoughtDefOf --> "NeuroquakeEcho" ThoughtDef
@enduml
