@startuml
class TransferableCountToTransferStoppingPoint <<struct>> {
    + threshold : int
    + leftLabel : string
    + rightLabel : string
    + TransferableCountToTransferStoppingPoint(threshold:int, leftLabel:string, rightLabel:string)
}
@enduml
