@startuml
class Trigger_WoundedGuestPresent {
    + Trigger_WoundedGuestPresent()
    + <<override>> ActivateOn(lord:Lord, signal:TriggerSignal) : bool
}
Trigger <|-- Trigger_WoundedGuestPresent
@enduml
