@startuml
class Trigger_KidnapVictimPresent {
    + Trigger_KidnapVictimPresent()
    + <<override>> ActivateOn(lord:Lord, signal:TriggerSignal) : bool
}
Trigger <|-- Trigger_KidnapVictimPresent
@enduml
