@startuml
class TurretTop {
    + {static} <<readonly>> ArtworkRotation : int
    + SetRotationFromOrientation() : void
    + TurretTop(ParentTurret:Building_Turret)
    + TurretTopTick() : void
    + DrawTurret() : void
}
@enduml
