@startuml
class WildAnimalSpawner {
    + AnimalEcosystemFull : bool <<get>>
    + WildAnimalSpawner(map:Map)
    + WildAnimalSpawnerTick() : void
    + SpawnRandomWildAnimalAt(loc:IntVec3) : bool
    + DebugString() : string
}
@enduml
