@startuml
class WorkGiver_Merge {
    + <<override>> MaxPathDanger(pawn:Pawn) : Danger
    + <<override>> PotentialWorkThingsGlobal(pawn:Pawn) : IEnumerable<Thing>
    + <<override>> ShouldSkip(pawn:Pawn, forced:bool) : bool
    + <<override>> JobOnThing(pawn:Pawn, t:Thing, forced:bool) : Job
}
WorkGiver_Scanner <|-- WorkGiver_Merge
@enduml
