@startuml
class WorkGiver_Strip {
    + <<override>> PotentialWorkThingsGlobal(pawn:Pawn) : IEnumerable<Thing>
    + <<override>> MaxPathDanger(pawn:Pawn) : Danger
    + <<override>> ShouldSkip(pawn:Pawn, forced:bool) : bool
    + <<override>> HasJobOnThing(pawn:Pawn, t:Thing, forced:bool) : bool
    + <<override>> JobOnThing(pawn:Pawn, t:Thing, forced:bool) : Job
}
WorkGiver_Scanner <|-- WorkGiver_Strip
WorkGiver_Strip --> "PathEndMode" PathEndMode
@enduml
