@startuml
class WorkGiver_RescueDowned {
    + <<override>> MaxPathDanger(pawn:Pawn) : Danger
    + <<override>> PotentialWorkThingsGlobal(pawn:Pawn) : IEnumerable<Thing>
    + <<override>> ShouldSkip(pawn:Pawn, forced:bool) : bool
    + <<override>> HasJobOnThing(pawn:Pawn, t:Thing, forced:bool) : bool
    + <<override>> JobOnThing(pawn:Pawn, t:Thing, forced:bool) : Job
}
WorkGiver_TakeToBed <|-- WorkGiver_RescueDowned
WorkGiver_RescueDowned --> "PathEndMode" PathEndMode
WorkGiver_RescueDowned --> "PotentialWorkThingRequest" ThingRequest
@enduml
