@startuml
class WorldObjectCompProperties_PrisonerWillingToJoin {
    + WorldObjectCompProperties_PrisonerWillingToJoin()
}
WorldObjectCompProperties <|-- WorldObjectCompProperties_PrisonerWillingToJoin
@enduml
