@startuml
class JobDriver_HaulToCell {
    + <<override>> ExposeData() : void
    + <<override>> GetReport() : string
    + <<override>> TryMakePreToilReservations(errorOnFailed:bool) : bool
    + <<override>> Notify_Starting() : void
}
JobDriver <|-- JobDriver_HaulToCell
@enduml
