@startuml
class MentalState_TargetedTantrum {
    + <<const>> MinMarketValue : int = 300
    + <<override>> MentalStateTick() : void
    + <<override>> PreStart() : void
    + <<override>> GetBeginLetterText() : string
}
MentalState_Tantrum <|-- MentalState_TargetedTantrum
@enduml
