@startuml
class MentalBreakWorker_RunWild {
    + <<override>> BreakCanOccur(pawn:Pawn) : bool
    + <<override>> TryStart(pawn:Pawn, reason:string, causedByMood:bool) : bool
}
MentalBreakWorker <|-- MentalBreakWorker_RunWild
@enduml
