@startuml
class ThinkResult <<struct>> {
    + Tag : JobTag? <<get>>
    + FromQueue : bool <<get>>
    + IsValid : bool <<get>>
    + ThinkResult(job:Job, sourceNode:ThinkNode, tag:JobTag?, fromQueue:bool)
    + <<override>> ToString() : string
    + <<override>> GetHashCode() : int
    + <<override>> Equals(obj:object) : bool
    + Equals(other:ThinkResult) : bool
}
class "IEquatable`1"<T> {
}
"IEquatable`1" "<ThinkResult>" <|-- ThinkResult
ThinkResult --> "Job" Job
ThinkResult --> "SourceNode" ThinkNode
ThinkResult --> "NoJob" ThinkResult
@enduml
