@startuml
class ThinkNode_FilterPriority {
    + minPriority : float = 0.5f
    + <<override>> DeepCopy(resolve:bool) : ThinkNode
    + <<override>> TryIssueJobPackage(pawn:Pawn, jobParams:JobIssueParams) : ThinkResult
}
ThinkNode <|-- ThinkNode_FilterPriority
@enduml
