@startuml
class ThinkNode_PrioritySorter {
    + minPriority : float
    + <<override>> DeepCopy(resolve:bool) : ThinkNode
    + <<override>> TryIssueJobPackage(pawn:Pawn, jobParams:JobIssueParams) : ThinkResult
}
ThinkNode <|-- ThinkNode_PrioritySorter
@enduml
