@startuml
class QuestNode_SetRoyalTitle {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_SetRoyalTitle
QuestNode_SetRoyalTitle --> "pawn<Pawn>" "SlateRef`1"
QuestNode_SetRoyalTitle --> "royalTitle<RoyalTitleDef>" "SlateRef`1"
QuestNode_SetRoyalTitle --> "faction<Faction>" "SlateRef`1"
@enduml
