@startuml
class QuestNode_RemoveEquipmentFromPawns {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_RemoveEquipmentFromPawns
QuestNode_RemoveEquipmentFromPawns --> "inSignal<string>" "SlateRef`1"
QuestNode_RemoveEquipmentFromPawns --> "pawns<IEnumerable<Pawn>>" "SlateRef`1"
@enduml
