@startuml
class QuestNode_IsSet {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_IsSet
QuestNode_IsSet --> "name<string>" "SlateRef`1"
QuestNode_IsSet --> "node" QuestNode
QuestNode_IsSet --> "elseNode" QuestNode
@enduml
