@startuml
class QuestNode_TradeRequest_RandomOfferDuration {
    + {static} RandomOfferDurationTicks(tileIdFrom:int, tileIdTo:int, travelTicks:int) : int
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_TradeRequest_RandomOfferDuration
QuestNode_TradeRequest_RandomOfferDuration --> "settlement<Settlement>" "SlateRef`1"
QuestNode_TradeRequest_RandomOfferDuration --> "storeAs<string>" "SlateRef`1"
QuestNode_TradeRequest_RandomOfferDuration --> "storeEstimatedTravelTimeAs<string>" "SlateRef`1"
@enduml
