@startuml
class QuestNode_DisableRandomMoodCausedMentalBreaks {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_DisableRandomMoodCausedMentalBreaks
QuestNode_DisableRandomMoodCausedMentalBreaks --> "inSignalEnable<string>" "SlateRef`1"
QuestNode_DisableRandomMoodCausedMentalBreaks --> "inSignalDisable<string>" "SlateRef`1"
QuestNode_DisableRandomMoodCausedMentalBreaks --> "pawns<IEnumerable<Pawn>>" "SlateRef`1"
@enduml
