@startuml
class QuestNode_Add {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_Add
QuestNode_Add --> "value1<double>" "SlateRef`1"
QuestNode_Add --> "value2<double>" "SlateRef`1"
QuestNode_Add --> "storeAs<string>" "SlateRef`1"
@enduml
