@startuml
class QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle
QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle --> "inSignal<string>" "SlateRef`1"
QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle --> "pawns<List<Pawn>>" "SlateRef`1"
QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle --> "faction<Faction>" "SlateRef`1"
QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle --> "goodwillChange<int>" "SlateRef`1"
QuestNode_ChangeGoodwillForAlivePawnsMissingFromShuttle --> "reason<string>" "SlateRef`1"
@enduml
