@startuml
class QuestNode_EndGame_ShipEscape_FindShipTile {
}
class "SlateRef`1"<T> {
}
QuestNode <|-- QuestNode_EndGame_ShipEscape_FindShipTile
QuestNode_EndGame_ShipEscape_FindShipTile --> "storeAs<string>" "SlateRef`1"
@enduml
