@startuml
class SlateNames <<static>> {
    + <<const>> Points : string = "points"
    + <<const>> RewardValue : string = "rewardValue"
    + <<const>> Map : string = "map"
    + <<const>> EnemyFaction : string = "enemyFaction"
    + <<const>> SiteDistRange : string = "siteDistRange"
    + <<const>> WalkInSpot : string = "walkInSpot"
    + <<const>> RaidPawnKinds : string = "raidPawnKinds"
    + <<const>> AllThreats : string = "allThreats"
    + <<const>> RaidArrivalModeInfo : string = "raidArrivalModeInfo"
    + <<const>> Asker : string = "asker"
    + <<const>> TitleHolder : string = "titleHolder"
    + <<const>> TitleHeir : string = "titleHeir"
    + <<const>> TitlePreviousHeir : string = "titlePreviousHeir"
    + <<const>> BestowingFaction : string = "bestowingFaction"
    + <<const>> AskerType : string = "askerType"
    + <<const>> ItemStashSingleThing : string = "itemStashSingleThing"
    + <<const>> ItemStashThings : string = "itemStashThings"
    + <<const>> InSignal : string = "inSignal"
    + <<const>> ResolvedQuestName : string = "resolvedQuestName"
    + <<const>> ResolvedQuestDescription : string = "resolvedQuestDescription"
    + <<const>> AnimalCount : string = "animalCount"
    + <<const>> AnimalKind : string = "animalKindDef"
    + <<const>> TargetMineable : string = "targetMineable"
    + <<const>> TargetMineableThing : string = "targetMineableThing"
    + <<const>> Worker : string = "worker"
    + <<const>> SameQuestsCount : string = "sameQuestsCount"
    + <<const>> TestRunCallback : string = "testRunCallback"
    + <<const>> AllowViolentQuests : string = "allowViolentQuests"
    + <<const>> Refugee : string = "refugee"
    + <<const>> Prisoner : string = "prisoner"
    + <<const>> GeneratedItemStashThings : string = "generatedItemStashThings"
    + <<const>> DebugDontGenerateRewardThings : string = "debugDontGenerateRewardThings"
    + <<const>> PermitFaction : string = "permitFaction"
    + <<const>> LandingCell : string = "landingCell"
    + <<const>> LaborersCount : string = "laborersCount"
    + <<const>> LaborersPawnKind : string = "laborersPawnKind"
    + <<const>> LaborersDurationDays : string = "laborersDurationDays"
    + <<const>> ConditionCauser : string = "conditionCauser"
    + <<const>> Population : string = "population"
}
@enduml
