@startuml
class SymbolResolver_BasePart_Outdoors_Leaf_Farm {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_BasePart_Outdoors_Leaf_Farm
@enduml
