@startuml
class SymbolResolver_OutdoorsCampfire {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_OutdoorsCampfire
@enduml
