@startuml
class SymbolResolver_BasePart_Outdoors_Division_Split {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_BasePart_Outdoors_Division_Split
@enduml
