@startuml
class SymbolResolver_BasePart_Outdoors_LeafDecorated_EdgeStreet {
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_BasePart_Outdoors_LeafDecorated_EdgeStreet
@enduml
