@startuml
class SymbolResolver_SingleThing {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_SingleThing
@enduml
