@startuml
class SymbolResolver_BasePart_Outdoors_LeafDecorated_RandomInnerRect {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_BasePart_Outdoors_LeafDecorated_RandomInnerRect
@enduml
