@startuml
class SymbolResolver_GenericRoom {
    + interior : string
    + useRandomCarpet : bool
    + allowRoof : bool = true
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_GenericRoom
@enduml
