@startuml
class SymbolResolver_BasePart_Outdoors_Leaf_Empty {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_BasePart_Outdoors_Leaf_Empty
@enduml
