@startuml
class SymbolResolver_FillWithThings {
    + <<override>> CanResolve(rp:ResolveParams) : bool
    + <<override>> Resolve(rp:ResolveParams) : void
}
SymbolResolver <|-- SymbolResolver_FillWithThings
@enduml
