@startuml
class InflateManager <<sealed>> {
    + InflateManager()
    + InflateManager(expectRfc1950HeaderBytes:bool)
}
enum InflateManagerMode {
    METHOD,
    FLAG,
    DICT4,
    DICT3,
    DICT2,
    DICT1,
    DICT0,
    BLOCKS,
    CHECK4,
    CHECK3,
    CHECK2,
    CHECK1,
    DONE,
    BAD,
}
InflateManager +-- InflateManagerMode
@enduml
