@startuml
class LordToilData_ExitMap {
    + canDig : bool
    + interruptCurrentJob : bool
    + <<override>> ExposeData() : void
}
LordToilData <|-- LordToilData_ExitMap
LordToilData_ExitMap --> "locomotion" LocomotionUrgency
@enduml
