@startuml
class LordToil_ExitMapTraderFighting {
    + <<override>> AllowSatisfyLongNeeds : bool <<get>>
    + <<override>> AllowSelfTend : bool <<get>>
    + <<override>> UpdateAllDuties() : void
}
LordToil <|-- LordToil_ExitMapTraderFighting
@enduml
