@startuml
class Trigger_FractionPawnsLost {
    + Trigger_FractionPawnsLost(fraction:float)
    + <<override>> ActivateOn(lord:Lord, signal:TriggerSignal) : bool
}
Trigger <|-- Trigger_FractionPawnsLost
@enduml
