@startuml
enum TriggerSignalType {
    Undefined,
    Tick,
    Memo,
    PawnDamaged,
    PawnArrestAttempted,
    PawnLost,
    BuildingDamaged,
    BuildingLost,
    FactionRelationsChanged,
    DormancyWakeup,
    Clamor,
    MechClusterDefeated,
    Signal,
}
@enduml
