@startuml
class WorkshopUtility <<static>> {
    + {static} GetLabel(stage:WorkshopInteractStage) : string
    + {static} GetLabel(status:EItemUpdateStatus) : string
    + {static} GetLabel(result:EResult) : string
}
@enduml
