@startuml
class SoundParamSource_CameraAltitude {
    + <<override>> Label : string <<get>>
    + <<override>> ValueFor(samp:Sample) : float
}
SoundParamSource <|-- SoundParamSource_CameraAltitude
@enduml
