@startuml
class SoundParamTarget_PropertyReverb {
    + <<override>> Label : string <<get>>
    + <<override>> SetOn(sample:Sample, value:float) : void
}
SoundParamTarget <|-- SoundParamTarget_PropertyReverb
SoundParamTarget_PropertyReverb --> "NeededFilterType" Type
@enduml
