@startuml
class CaravanArrivalAction_Trade {
    + <<override>> Label : string <<get>>
    + <<override>> ReportString : string <<get>>
    + CaravanArrivalAction_Trade()
    + CaravanArrivalAction_Trade(settlement:Settlement)
    + <<override>> StillValid(caravan:Caravan, destinationTile:int) : FloatMenuAcceptanceReport
    + <<override>> Arrived(caravan:Caravan) : void
    + <<override>> ExposeData() : void
    + {static} CanTradeWith(caravan:Caravan, settlement:Settlement) : FloatMenuAcceptanceReport
    + {static} GetFloatMenuOptions(caravan:Caravan, settlement:Settlement) : IEnumerable<FloatMenuOption>
}
CaravanArrivalAction <|-- CaravanArrivalAction_Trade
@enduml
