@startuml
class PrisonerWillingToJoinComp {
    + <<override>> CompInspectStringExtra() : string
}
ImportantPawnComp <|-- PrisonerWillingToJoinComp
IThingHolder <|-- PrisonerWillingToJoinComp
@enduml
