@startuml
class SitePartDefWithParams {
    + SitePartDefWithParams(def:SitePartDef, parms:SitePartParams)
}
SitePartDefWithParams --> "def" SitePartDef
SitePartDefWithParams --> "parms" SitePartParams
@enduml
