@startuml
class WorldGenStep_Terrain {
    + <<override>> SeedPart : int <<get>>
    + <<override>> GenerateFresh(seed:string) : void
    + <<override>> GenerateFromScribe(seed:string) : void
}
WorldGenStep <|-- WorldGenStep_Terrain
@enduml
